#975 Use v-safe-html instead of v-html
okTurtles/group-income pull request #1064
Opened 2021-05-01 06:06 UTC by snowteamer

Closes #975

### Summary of changes:
- New `v-safe-html` copied from GitLab UI with minor changes.
- New `disallow-vhtml-directive` pug-lint rule, to automate `v-html` usage detection.
- Every usage of the `v-html` directive has been replaced with `v-safe-html`.
- Usage of `innerHTML` assignment in `SendArea.vue` has been replaced by `textContent` assignment.

2021-05-04 12:44 UTC, taoeffect requested changes
Very nice PR @snowteamer!

I tested it out to see if it would stop `xss"'><img src=x onerror=alert(document.domain)>` from working in the contributions field or in the group name and it didn't. :-\

<img width="479" alt="Screen Shot 2021-05-04 at 3 39 35 PM" src="https://user-images.githubusercontent.com/138706/117004805-2a31cc80-acef-11eb-81fa-7f37ab1a3a60.png">
<img width="540" alt="Screen Shot 2021-05-04 at 3 39 13 PM" src="https://user-images.githubusercontent.com/138706/117004813-2ef68080-acef-11eb-8a5f-f96d30c83ea3.png">
<img width="857" alt="Screen Shot 2021-05-04 at 3 34 25 PM" src="https://user-images.githubusercontent.com/138706/117004819-3027ad80-acef-11eb-842c-5438f63423b6.png">

2021-05-05 17:05 UTC, snowteamer commented
It looks like another kind of vulnerability is involved here, unrelated to `v-html` or `innerHTML` usage but rather to pug templates: 

For example, the issue with group name vulnerability seem to arise from [GroupWelcome.vue](https://github.com/okTurtles/group-income-simple/blob/7693b98575f8746fd26dd0e6fab9afc2ac63d899/frontend/views/components/GroupWelcome.vue#L9-L13), where `groupName` gets included in the HTML despite coming from unsanitized user input.

I think a possible solution would be the sanitization of every textual user input. Patching places where  `v-html` or `innerHTML` are used is not enough to secure the application.

2021-05-06 10:03 UTC, taoeffect commented
@snowteamer I was a bit confused by the example you gave, but then realized what the confusion was. `{groupName}` is not Vue.js [template syntax](https://vuejs.org/v2/guide/syntax.html), which AFAIK doesn't have this problem, [but rather it is our custom `i18n` translation stuff](https://github.com/okTurtles/group-income-simple/blob/master/frontend/views/utils/translations.js#L137-L160).

That's what needs to be updated to address this. I see there is at least one assignment there to `innerHTML`, and there might be something else that needs to be modified.

2021-05-10 15:27 UTC, snowteamer commented
Some of our i18n component instances contain an embedded anchor link, so we have to allow `<a>` tags as well as the `href` attribute in the `dompurify` config when sanititizing those strings, which might however be unsafe if user input is injected.

Besides, things such as group names or user names are plain text, and should likely not contain any character specific to JS or HTML such as `<>/\()"'&` (although `&` and `/` might be allowed if followed by a plain white space, to enable e.g. groupe names such as Turtles & Friends).

Therefore I think we need both
- whole i18n string sanitization (allowing only tags and attributes required for correct rendering),
- and thorough user input validation, both client-side and server-side. We probably don't want to store malicious input, even if we sanitize it every time before rendering. This could also solve #902.

@joepie91 I'm not really a security expert, so your expertise would be much appreciated here!

2021-05-14 15:16 UTC, joepie91 commented
@snowteamer I won't be available going forward, but I'll try to answer your question as best as I can here:

> We probably don't want to store malicious input, even if we sanitize it every time before rendering. 

Storage-wise, there is no such thing as "malicious input", and so input should be stored as-is. Until the point of use, it's just a string of characters with no special meaning, and importantly, *which* characters have special meaning will change over time as you target different output forms.

The typical example of this is people who HTML-escape values before storing them; then later they decide to build a JSON API, and suddenly their JSON responses incorrectly contain HTML entities, because an assumption of "only HTML" as the output format was encoded into the stored data. Now HTML-escaping is reversible, so it's at least fixable, but many other 'input validation' approaches are lossy and essentially result in irrevocable data corruption.

Therefore, the stored data should always be the original data as-is, and it's the rendering logic that should process it in a manner appropriate to the rendering context. In most cases (eg. modern templaters, React, JSON encoders, etc.) that does not require any special actions, as you are *already* specifying the text separately from the markup/structure, and so the encoder will automatically escape as-needed.

However...

> Some of our i18n component instances contain an embedded anchor link, so we have to allow <a> tags as well as the href attribute in the dompurify config when sanititizing those strings, which might however be unsafe if user input is injected.

That's a trickier case. Essentially, your rendering target is now not "the page", but "the i18n implementation", and the actual rendering-to-page will have to be a direct raw HTML insert due to the i18n implementation outputting structurally significant HTML.

In practice, however, that just means that the "point of rendering" changes - now, instead of escaping content prior to injection into the page, you need to escape content *prior to injection into the i18n string* (which presumably also happens at rendering time). That way, the user-specified parts of the resulting string have been 'immunized' upfront and so any actual HTML output can be assumed to have come from the i18n templates.

> Besides, things such as group names or user names are plain text, and should likely not contain any character specific to JS or HTML such as <>/\()"'& (although & and / might be allowed if followed by a plain white space, to enable e.g. groupe names such as Turtles & Friends).

I would recommend against introducing character set restrictions for this reason. It's a much less reliable approach than just doing eg. HTML-escaping, while also inconveniencing the user, and it's risky from a future perspective - you might decide today to not allow 'dangerous characters', but a future developer won't be aware of the reasons for that decision, and in the future might go "hmm, strange, brackets are not allowed, dunno why, let's enable them because this user asked for it" and then you have a security issue.

As a general rule, assumptions are the most dangerous thing in building secure software; every assumption you make that isn't enforced in some way, is likely to bite you later when everybody has forgotten about the original assumption. Ideally your code should continue to function safely *in spite of* such assumptions.

> whole i18n string sanitization (allowing only tags and attributes required for correct rendering),

I do think this is useful as a defense-in-depth measure (being essentially zero-cost), so long as it's explicitly documented (eg. with a comment) that it's an *additional* safeguard, and should not be relied upon. In particular, things like `javascript:` URLs as the `href` are still risky, and this should mainly serve to eliminate malicious input that survived HTML-escaping and/or URL validation due to a hypothetical implementation bug.

2021-05-15 06:44 UTC, snowteamer commented
@joepie91 Though you might not read this until you are back, I wish to thank you for taking the time to write up this thorough and insightful answer.

Things are much clearer now thanks to your advice!

2021-06-19 01:01 UTC, taoeffect reviewed
Fantastic work @snowteamer! Tested & verified! 😄 🎉 

Consider this comment an approval on the PR and the approach!

Only a minor issue I noticed with a placement of a comment. As you mentioned that you wanted first to OK to approve the approach before modifying other files using this approach, I'm leaving this as a comment instead of marking the PR approved. Let us know on Slack when it's ready for the final approval!

2021-06-19 01:01 UTC, taoeffect commented on frontend/views/utils/safeLinkTag.js
> +}
Nice, looks bullet-proof to me. 👍

2021-06-19 01:01 UTC, taoeffect commented on frontend/views/utils/vSafeHtml.js
> +  ALLOWED_ATTR: ['class'],
I am a bit confused by the comment above here, as it refers to `'href'` and `'target`' attrs, but they don't appear in this list here.

OTOH they are included and merged in the file `translations.js`, so should this comment be moved there?

2021-06-20 01:30 UTC, snowteamer commented on frontend/views/utils/vSafeHtml.js
> +  ALLOWED_ATTR: ['class'],
Indeed, I overlooked this.

2021-06-21 19:43 UTC, closed without merging