Add system colors theme
okTurtles/group-income pull request #1287
Opened 2022-05-30 12:21 UTC by pieer

2022-06-01 01:06 UTC, taoeffect requested changes
Review done! Nice job @pieer! 👍 

Found some minor issues, but also, for some reason in Firefox the theme isn't getting updated when I switch the system theme:

<img width="890" alt="Screen Shot 2022-05-31 at 6 06 00 PM" src="https://user-images.githubusercontent.com/138706/171307902-13f568b7-c593-4811-9873-70b836b8f36e.png">

I even refreshed the page and it still isn't switching.

2022-06-01 01:06 UTC, taoeffect commented on frontend/views/containers/user-settings/ThemeSvg.vue
> +  name: 'SelectorThemeSVG',
Shouldn't this name match the name of the file?

2022-06-01 01:06 UTC, taoeffect commented on frontend/views/containers/user-settings/Theme.vue
> +        span Use system settings
Missing `i18n`

2022-06-01 01:06 UTC, taoeffect commented on frontend/views/containers/user-settings/Theme.vue
> +        span Use system settings
Missing `i18n`

2022-06-27 17:12 UTC, taoeffect requested changes
@pieer Same issue.

Refreshing page after changing os theme doesn't update.

Ideally it will also update without a refresh if set to system theme and system theme changes.

2022-07-06 01:25 UTC, taoeffect reviewed
I know you said you're still working on this, but just an update, I tried out the latest changes you pushed and indeed, the problem still exists. I didn't notice a difference, refreshing the page still doesn't fix it.

2022-07-08 11:37 UTC, pieer commented
> I didn't notice a difference, refreshing the page still doesn't fix it.

Weird, it's working well on my mac on firefox when I change the system settings appearance...
Could you help me to find what's the difference?
I sent you a video on Slack

2022-07-08 14:31 UTC, taoeffect commented on frontend/model/state.js
> +      store.commit('setTheme', 'system')
Why is there `store.commit('setTheme', THEME_DARK)` here?

2022-07-14 10:18 UTC, pieer commented on frontend/model/state.js
> +      store.commit('setTheme', 'system')
I found the solution I think in the new PR: update the state of the colors instead of the state of the theme

2022-07-15 12:41 UTC, taoeffect commented on frontend/model/state.js
> +  themeColor:
Bug here causing travis to fail

2022-07-17 10:16 UTC, taoeffect requested changes
@pieer - Great work, and sorry again that I didn't realize that Firefox Developer Edition has a unique setting that prevented me from properly testing this PR before.

This time I've done a thorough test and also a thorough review of the code, and made some suggestions for how to simplify some of the code.

Also, I'm encountering a weird issue when changing the system theme in the System Preferences, and I verified this on both Firefox and Safari.

When I set it to "System" theme and use System Preferences to switch back and forth between the system theme while in the Appearance preferences, it doesn't switch the colors for everything and I'm not sure why.

Notice here when I switched to "Light Theme" in System Preferences the menu items didn't change their color:

<img width="1260" alt="Screen Shot 2022-07-17 at 6 15 07 PM" src="https://user-images.githubusercontent.com/138706/179393677-0bfd4900-c587-464c-afca-f887e261fc64.png">

And similar issue when switching back to the dark theme (notice the background shadow is white), although this only happens sometimes (I can't always reproduce it):

<img width="870" alt="Screen Shot 2022-07-17 at 7 03 53 PM" src="https://user-images.githubusercontent.com/138706/179393702-1ff7f1c6-d15c-4304-8524-6df597299137.png">

If you can't figure this out it's OK, not a big deal since refreshing the page fixes the problem! I'm mainly concerned with some code simplification (see comments).

2022-07-17 10:16 UTC, taoeffect commented on frontend/model/state.js
> +    store.commit('setColors', checkSystemColor())
For consistency and easy-of-readability sake, and since `setColors` doesn't actually take a parameter, and so that we’re not storing the entire theme data in local storage, I recommend the following changes:

- Rename the parameter in this function to `theme`
- Remove `setColors` mutation, and set the colors directly inside this function:

```js
  setTheme (state, theme) {
    state.theme = theme
    state.themeColor = theme === 'system' ? checkSystemColor() : theme
  },
```

And then modify the lines up above to:

```js
const defaultTheme = 'system'
const defaultColor = checkSystemColor()

if (window.matchMedia) {
  window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', e => {
    if (store.state.theme === 'system') {
      store.commit('setTheme', 'system')
    }
  })
}
```

And the `colors` getter below to:

```js
  colors (state) {
    return Colors[state.themeColor]
  },
```

2022-07-17 10:16 UTC, taoeffect commented on frontend/model/state.js
> +}
Since `window` is guaranteed to be defined, we don't need to check if it's defined and this function could be simplified to:

```js
const checkSystemColor = () => {
  return window.matchMedia?.('(prefers-color-scheme: dark)').matches
    ? THEME_DARK
    : THEME_LIGHT
}
```

2022-07-17 10:16 UTC, taoeffect commented on frontend/views/containers/user-settings/Theme.vue
> +      'colors',
AFAICT, `colors` is no longer used in this file so doesn't need to be here.

2022-07-17 10:16 UTC, taoeffect commented on frontend/model/state.js
> +  })
- If debug logging is still needed, please change to `console.debug`, otherwise please remove logging
- It's possible to simplify the code by calling `setTheme` here instead of `setColors`, see comment below about `setTheme`

2022-07-17 20:45 UTC, pieer commented on frontend/model/state.js
> +    store.commit('setColors', checkSystemColor())
Thanks for the feedbacks. I fix all the issues and simplify the code according to your help

2022-07-17 20:46 UTC, pieer commented on frontend/model/state.js
> +}
Fixed

2022-07-17 20:58 UTC, pieer commented on frontend/model/state.js
> +  })
All done

2022-07-17 21:37 UTC, taoeffect approved these changes
Excellent!

2022-07-17 21:37 UTC, merged