Move app settings into their own Vuex module
okTurtles/group-income pull request #1347
Opened 2022-07-13 22:04 UTC by snowteamer

Closes #1344
Closes #1276

### Summary of changes:
- Settings like `appLogsFilter`, `fontSize`, `theme` etc. have been moved to `@model/settings/vuexModule.js`.
- They should now correctly revert to their default values upon successfully logging out.
- If a `?debug` query parameter is present and truthy, then debug- and log-level applications logs will be enabled by default. Users can still disable them later via the Application Logs modal though.

2022-07-14 06:04 UTC, taoeffect reviewed
Not a review but some questions for now.

2022-07-14 06:04 UTC, taoeffect commented on frontend/views/containers/user-settings/AppLogs.vue
> +              input.input(type='checkbox' name='filter' v-model='form.filter' value='debug' checked)
Why is the checked attribute for Debug and Log being modified?

2022-07-14 06:04 UTC, taoeffect commented on frontend/model/settings/vuexModule.js
> +'use strict'
A folder is usually needed when there are more than one related files. But this folder contains only a single file... so why not just have it be `settings.js`?

2022-07-15 10:26 UTC, snowteamer commented on frontend/views/containers/user-settings/AppLogs.vue
> +              input.input(type='checkbox' name='filter' v-model='form.filter' value='debug' checked)
That's a mistake of mine - I've read that these attributes are ignored when v-model is provided, so I first removed them. Then I thought I'd better do that later, so I added them back, albeit with this mistake.

2022-07-15 10:28 UTC, snowteamer commented on frontend/model/settings/vuexModule.js
> +'use strict'
For consistency with the notification module, which has the same folder structure, although it contains more files.

2022-07-15 11:22 UTC, taoeffect commented on frontend/model/settings/vuexModule.js
> +'use strict'
ok, make sense 👍

2022-07-22 09:22 UTC, taoeffect requested changes
Nice work @snowteamer - just a heads up - recent changes to `master` added a new setting (`notificationEnabled`) that needs to be merged with this PR.

2022-07-22 09:22 UTC, taoeffect commented on frontend/model/contracts/manifests.json
> +  "manifests": {}
(Somehow my comment here got lost.)

This needs to not be empty. After merging `master` (which may fix this problem all on its own), be sure to run `grunt dev` at least once. The hashes should match and this file should be without modifications since it doesn't contracts.

2022-08-03 17:14 UTC, closed without merging