Sebin/task/#1303 implment generic proposal modal
okTurtles/group-income pull request #1353
Opened 2022-07-17 05:41 UTC by SebinSong

work for #1303

2022-07-17 08:19 UTC, taoeffect requested changes
Excellent @SebinSong! Nicely done!

A few minor change requests:

### Icon

Here the icon looks like a bar graph:

<img width="107" alt="Screen Shot 2022-07-17 at 5 13 56 PM" src="https://user-images.githubusercontent.com/138706/179389871-257fe918-6fdd-43ea-a348-82f067c17f9c.png">
 
And to be honest, that seems like a decent choice for it. However, the designs have this icon (and corresponding dark version):

<img width="61" alt="Screen Shot 2022-07-17 at 5 14 38 PM" src="https://user-images.githubusercontent.com/138706/179389888-cbb34f7c-74c3-4571-9f63-1d2fac5d4302.png">

How difficult would it be to switch to that?

### Regenerate `contracts/0.0.1`

Since this PR modifies the contracts code we need to freeze this version of the contracts in time.

We do this once for each version release of the contracts. Right now we are on version 0.0.1 of the contracts, which are saved here: `contracts/0.0.1`, but since we haven't released them we are overwriting that version each time the contracts code is modified.

So to do this with your PR (since it modifies the `group.js` contract by modifying `shared/voting/proposals.js`), do the following:

1. Delete the folder `contracts/0.0.1`
2. Run `grunt pin:0.0.1`

And this needs to be done each time you make modifications to the contracts part of the code. Unless we've begun working on a new release (in which case you'd do `grunt pin:0.0.2`).

### See comment

One minor improvement in ProposalItem.vue, see comments.

2022-07-17 08:19 UTC, taoeffect commented on frontend/views/containers/proposals/ProposalItem.vue
> +        [PROPOSAL_GENERIC]: () => `${this.proposal.data.proposalData.name}`
Since you're not returning a modified version of the string, there's no need to wrap this in backticks. Just return the value.

2022-07-18 07:29 UTC, SebinSong commented
@taoeffect worked on all your change requests in [this commit](https://github.com/okTurtles/group-income/pull/1353/commits/fafd0b09c94ee378e7a436f0c578944f5f743f9b). pls let me know if there's additional thing to be done.

2022-07-23 08:09 UTC, taoeffect reviewed
Nice work @SebinSong, have a question and found a weird bug... see comment

2022-07-23 08:09 UTC, taoeffect commented on frontend/views/containers/proposals/ProposalTemplate.vue
> +        slot(name='reason')
This looks like a significant change, did you double-check everything related to this to make sure it still works?

Also, I don't know if this bug is related to this, or to a different recent PR having to do with the `Enter` key being pressed that I didn't catch in my review (#1360), but when I created a group with 1 user, and went to create a proposal to change the mincome, and pressed Enter after entering the new mincome, this error came up:

<img width="1389" alt="Screen Shot 2022-07-23 at 5 07 19 PM" src="https://user-images.githubusercontent.com/138706/180596562-dd16b173-9c85-423f-b36d-2ff037dfd02f.png">

Do you think you could track it down?

2022-07-23 08:49 UTC, SebinSong commented
@taoeffect
A fix for this issue has been made in [this commit](https://github.com/okTurtles/group-income/pull/1353/commits/d32b5975892c3dd31e8dbdda1abb6922a2109644)

Firstly, this issue isn't related to slot(name='reason') I created but while looking into the issue, I noticed this slot is not being used anywhere, so have deleted & reverted it back to what it was in ProposalTemplate.vue

Secondly, the cause of the issue was Mincome.vue trying to reference the the error-banner after it being destroyed. but that's only the case when this.groupShouldPropose is false, which matches your scenario where the group member is only one.

Pls let me know if you spot any other issue in this PR.

2022-07-23 08:56 UTC, taoeffect approved these changes
Approved! Great work @SebinSong! 😄

2022-07-23 08:56 UTC, merged