#1362 implement dropdown for proposals
okTurtles/group-income pull request #1368
Opened 2022-07-27 10:04 UTC by SebinSong

working on the issue #1362

2022-08-03 06:30 UTC, taoeffect requested changes
Thanks for sending this in @SebinSong!

I couldn't figure out how to test this though, as the proposals widget doesn't show up at all in one case, and when there's a proposal the dropdown menu still doesn't seem to be visible either:

<img width="845" alt="Screen Shot 2022-08-03 at 3 26 56 PM" src="https://user-images.githubusercontent.com/138706/182539551-903ab0db-6fd8-4e56-b388-725b0e103e76.png">

<img width="847" alt="Screen Shot 2022-08-03 at 3 28 53 PM" src="https://user-images.githubusercontent.com/138706/182539574-afa76bbd-3255-4d51-9840-f76af65db2cb.png">

2022-08-03 06:30 UTC, taoeffect commented on frontend/views/containers/dashboard/GroupMembersAllModal.vue
> +                @click.stop='removeMember'
So this `removeMember` method doesn't actually do anything. Do you think you can fill it in?

2022-08-03 06:30 UTC, taoeffect commented on frontend/views/containers/chatroom/GroupMembersDirectMessages.vue
> +  name: 'GroupMembersDirectMessages',
Nice catch! 👍

2022-08-03 06:30 UTC, taoeffect commented on frontend/views/components/ButtonDropdownMenu.vue
> +       */
Nice, clear comment 👍

2022-08-04 06:03 UTC, SebinSong commented
@taoeffect 
I have no idea how you got that 'Create Generic proposal' button. are you testing it in the correct branch?
[`sebin/task/#1362-implement-dropdown-for-proposals`](https://github.com/okTurtles/group-income/tree/sebin/task/%231362-implement-dropdown-for-proposals)

2022-08-04 06:38 UTC, taoeffect requested changes
Sebin - you're right, I must have been testing some other PR by accident, thinking it was this one. Doh! 😖

OK, so - going back to this PR. Then it seems like there's two main issues:

1. The `GroupMembersAllModal.vue` should implement `removeMember`. It should be easy, just copy/paste the code that exists in the button for "Remove Member" when you click on a username.
2. As shown in your bottom screenshot - for some reason there's additional text beneath the proposals starting with "In Group Income..." That needs to not be there.

2022-08-04 07:24 UTC, SebinSong commented
@taoeffect Thanks,


> The GroupMembersAllModal.vue should implement removeMember. 

Done.

> As shown in your bottom screenshot - for some reason there's additional text beneath the proposals starting with "In Group Income..." That needs to not be there.

Done.

And also worked on resolving below issue. 

> I couldn't figure out how to test this though, as the proposals widget doesn't show up at all in one case

The dashboard does show this `CalloutCard` now when there's no proposals to display.

![image](https://user-images.githubusercontent.com/17641213/182785835-ec2d4c01-d788-4ce0-a6d0-cab74e4301f4.png)

 _But this leads to the following question._

**Q.** Don't we need to display some of the items under certain conditions? Like what I wrote in below screenshot?(Pls go ahead correct me if any of them are wrong)
![image](https://user-images.githubusercontent.com/17641213/182784019-0675c20d-4460-46a6-a522-1936d3e7f072.png)

Cheers,

2022-08-04 07:51 UTC, taoeffect commented
@SebinSong - great updates!

And yes - I agree with your proposal above, especially because with it it, it seems weird things happen like this:

![Screenshot 2022-08-04 at 16-50-20 Group Dashboard](https://user-images.githubusercontent.com/138706/182793656-25a039db-b131-4040-b5e5-eba5ec567bff.png)

2022-08-05 12:18 UTC, SebinSong commented
@taoeffect updated the PR with a change where some menu items are disabled under certain conditions.

2022-08-07 09:21 UTC, taoeffect approved these changes
Excellent work @SebinSong! Approved!

2022-08-07 09:21 UTC, merged