Move app settings into their own Vuex module
okTurtles/group-income pull request #1373
Opened 2022-08-03 17:21 UTC by snowteamer

Closes https://github.com/okTurtles/group-income/issues/1344
Closes https://github.com/okTurtles/group-income/issues/1276

### Summary of changes:

- Settings like appLogsFilter, fontSize, theme etc. have been moved to `@model/settings/vuexModule.js`.
- They should now correctly revert to their default values upon successfully logging out.
    If a `?debug` query parameter is present and truthy, then debug- and log-level applications logs will be enabled by default.
    Users can still disable them later via the Application Logs modal though.

2022-08-04 06:08 UTC, taoeffect requested changes
Great work @snowteamer!

I tested adjusting some settings, and while most seem to work, changing the system theme from Dark to Light and back while the settings are set to "System" doesn't work. I tried in both Firefox Developer Edition (with preferences set to "System") and also with Safari.

2022-08-15 10:53 UTC, corrideat approved these changes, later dismissed

2022-08-15 10:53 UTC, corrideat commented on Gruntfile.js
> +    const manifests = Object.fromEntries(Array.from(stdout.replace(/\\/g, '/').matchAll(r), x => [`gi.contracts/${x[1]}`, x[2]]))
Is this some Windows-related change? Either `/` or `\\` should be valid FS path separators

2022-08-30 01:51 UTC, taoeffect commented
It's surprising that this is failing repeatedly, even after `master` is merged.

@snowteamer what's your thinking about what might be the problem? Maybe it's a real bug in the PR?

2022-11-06 11:09 UTC, closed without merging