#658 Add a profile picture editor - Chunk 1
okTurtles/group-income pull request #1442
Opened 2022-10-20 07:55 UTC by SebinSong

Working on the **Chunk 1** from [this comment](https://github.com/okTurtles/group-income/issues/658#issuecomment-1280324328) in the issue.

2022-10-25 21:59 UTC, taoeffect reviewed
Excellent work @SebinSong! This is looking really great! 😄 

Some quick feedback on things I noticed:

- User can drag the image anywhere - it should be bounded by the image itself, right?
- When testing mobile in FFDevEdition and updating my profile picture (in responsive mobile mode), I wasn't able to drag the zoom sliders for some reason.

2022-10-26 05:06 UTC, SebinSong commented
@taoeffect 
Updated the PR with the fix for those issues.

> When testing mobile in FFDevEdition and updating my profile picture (in responsive mobile mode), I wasn't able to drag the zoom sliders for some reason.

I did see this happening in Firefox devtool too but when I tried the same in chrome devtool everything works fine as you can see from below video.

https://user-images.githubusercontent.com/17641213/197938691-0b2d186e-757f-47a0-bd42-b02e5ec2eec0.mp4

More importantly, I tried it on my android phone (on chrome browser via the browsersync external link- http://172.30.1.56:3000), It did work fine there too. It seems like a bug on firefox dev edition itself. :)

Thanks,

2022-10-26 21:41 UTC, taoeffect requested changes
Very clean and nicely done @SebinSong!

Minor comments-  also, it still allows me to drag the images beyond their borders / outside of their own bounding box.

![Screen Shot 2022-10-26 at 2 13 24 PM](https://user-images.githubusercontent.com/138706/198143760-dde29c3e-cbbe-412f-bc51-870e37704643.jpg)

2022-10-26 21:41 UTC, taoeffect commented on frontend/views/components/avatar-editor/AvatarEditorModal.vue
> +      ) Save
Missing i18n, try with `tag='button'` and `tag='button-submit'`, or include a child `i18n` element

2022-10-27 06:23 UTC, SebinSong commented
@taoeffect  thanks for review. 

Thought I would need a help with clarifying what the below requirement means.
> it still allows me to drag the images beyond their borders / outside of their own bounding box.

Does this mean that the the clipping circle should never leave the boundary of the image? For example,

<img src='https://user-images.githubusercontent.com/17641213/198205798-2f1bd605-2498-46b5-9db5-3c55c438a63f.png' width='630' > 

The red boundary is the bounding-box of the image on the canvas, whose size can change as the user zooms in & out of the image. Does moving(or translating) the image have to be limited to the points where the clipping circle never goes beyond the four edges of the red-boundary here?
Hope my drawing is being helpful here. :)

2022-10-27 08:24 UTC, SebinSong commented
@taoeffect 
here is the video demonstration of what I commented above.


https://user-images.githubusercontent.com/17641213/198231509-85525a99-cf6a-4e29-b92b-4ae0b43d2b1f.mp4

2022-10-27 21:44 UTC, taoeffect commented
@SebinSong Exactly right! 👍

2022-10-28 14:13 UTC, SebinSong commented
@taoeffect updated the PR with the work for the change request.

2022-10-29 01:46 UTC, taoeffect approved these changes
Brilliant! 🥇 😄 🎉

2022-10-29 01:46 UTC, merged