#1125 Ask users for income details update if mincome has been increased.
okTurtles/group-income pull request #1470
Opened 2022-12-03 04:00 UTC by SebinSong

closes #1125

2023-01-04 22:51 UTC, taoeffect requested changes
Excellent work @SebinSong 💪 

Review ready!

2023-01-04 22:51 UTC, taoeffect commented on frontend/controller/actions/group.js
> +      sbp('okTurtles.events/emit', REPLACE_MODAL, 'IncomeDetails')
This should be `REPLACE_MODAL` and not `OPEN_MODAL` (you're sure?)

2023-01-04 22:51 UTC, taoeffect commented on frontend/model/contracts/group.js
> +        }),
A few concerns here:

1. This is less elegant than the validation we had before, and there's a way to do this without having to modify the validation
2. By allowing `from` to be specified, we allow nonsensical actions to be created with invalid `from` values, and we also force the calling code to remember what the previous value was when creating this action

Instead, you can do most of what you need to do inside of the `process` by:

1. Caching the old value in the `process` function
2. Creating a new method under `methods:` key (see bottom of file)
3. Calling that method using `'gi.contracts/group/pushSideEffect'` and passing in the cached old mincome value

2023-01-04 22:51 UTC, taoeffect commented on frontend/model/contracts/shared/voting/proposals.js
> +        },
This can then be reverted

2023-01-04 22:51 UTC, taoeffect commented on frontend/views/containers/notifications/NotificationList.vue
> +          sbp(...item.sbpInvocation)
This is a cool idea 👍

2023-01-05 00:38 UTC, SebinSong commented on frontend/controller/actions/group.js
> +      sbp('okTurtles.events/emit', REPLACE_MODAL, 'IncomeDetails')
@taoeffect Yes, at the point in the flow, the `Prompt.vue` is active by the `sbp('gi.ui/prompt')` call few lines above.

2023-01-05 00:41 UTC, taoeffect commented on frontend/controller/actions/group.js
> +      sbp('okTurtles.events/emit', REPLACE_MODAL, 'IncomeDetails')
OK, possibly worth adding a comment to explain that, as to me it's not intuitive why that is, and the comment will prevent someone from accidentally modifying this to `OPEN_MODAL`

2023-01-05 09:18 UTC, SebinSong commented on frontend/model/contracts/group.js
> +        }),
great to know `methods` can be useful for similar cases (when certain data needs to be passed from 'process' to 'sideeffect') in the future. 👍

2023-01-05 09:47 UTC, SebinSong commented
@taoeffect I got one question here.
I just found this sentence from the issue description.
> Related to https://github.com/okTurtles/group-income/issues/952 - this issue addresses the problem of what needs to be done when the mincome changes and **the user is pledging.**

The way I've implemented it now is the notification and the prompt modal is sent & displayed to any group members who has entered their income details. should we do these only for pledging members? Thanks,

2023-01-05 13:40 UTC, taoeffect commented
@SebinSong 

> The way I've implemented it now is the notification and the prompt modal is sent & displayed to any group members who has entered their income details. should we do these only for pledging members? Thanks,

Let's consider a scenario where the mincome was $1000/month, and a user is a receiver, with an income of $500/month:

- If the mincome increases to $1400/month, no action is needed for this user. The algorithm correctly recalculates everything
- If the mincome decreases to $600/month, no action is needed.
- If the mincome decreases to $400/month, we should automatically switch them to being a pledger with a $0 pledge, and we should prompt them to update their income details per this PR

Issue #952 is about this automatic sort of adjustment, that we currently don't do.

2023-01-05 21:58 UTC, SebinSong commented
@taoeffect Thanks for clarification.
Could you confirm if my summary below is correct again? :)

[ Pledging members ]
- When mincome has increased: prompt them to update their income details
- When mincome has decreased: No action needed

[ Receiving members ]
- When mincome has increased: No action needed
- When mincome has decreased: If the decreased value is still higher than their monthly income, no action is needed. But if the updated mincome is lower than their monthly income, automatically switch them to a pledging member and prompt them to update their income details.

Btw,
> if the updated mincome is lower than their monthly income, automatically switch them to a pledging member
is apparently not implemented yet either. I can work on it as part of this PR if there isn't any reason that it has to be dealt with separately.

Thanks,

2023-01-05 22:00 UTC, taoeffect commented
Yep! That all sounds good 👍 

> automatically switch them to a pledging member

Yes, and specifically a pledging member with a 0 pledge.

2023-01-07 00:26 UTC, SebinSong commented on frontend/model/contracts/group.js
> +        await sbp('gi.actions/group/groupProfileUpdate', {
@taoeffect 
This part of the code is the source of below issue which I had trouble finding the cause for.

<img src='https://user-images.githubusercontent.com/17641213/211121117-45f0447e-8ffd-4bfa-89cf-fa9386ade359.png' width='410'>

Steps to reproduce / encounter this issue is:
1) Sign up `user-1` and then create a `group-1`(whose mincome is set to, let's say, 150$). then set up his income details as a pledger.
2) Sign up `user-2` and then join  him `group-2`. then set up his income details as a receiver with the income as let's say, 120$.
3) switch to `user-1` and reset the mincome to an amount lower than `user-2`'s income (e.g. 110$)
4) In `user-2`'s screen, we get this error.

2023-01-07 00:39 UTC, taoeffect commented on frontend/model/contracts/group.js
> +          const { loggedIn } = sbp('state/vuex/state')
Can't access state outside of contract state inside of a `process` function. `sbp('state/vuex/state')` can only be called inside of a sideEffect.

2023-01-09 23:26 UTC, taoeffect commented
One request from @dotmacro (that I think is a good one): [in the scenarios you described here](https://github.com/okTurtles/group-income/pull/1470#issuecomment-1372831162), where it says "no action needed", can you still prompt the **receiving** members (with the original prompt) to verify their income hasn't changed?

It's good to periodically prompt them tbh.

2023-01-10 03:28 UTC, SebinSong commented
@taoeffect @dotmacro Updated the PR with the work for the latest minor requirement.

2023-01-10 15:38 UTC, taoeffect requested changes
Excellent work @SebinSong! All of the code seems solid now.

I have now gone into the testing phase of the review, and have one concern / possible behavior change request. Have a look:

2023-01-10 15:38 UTC, taoeffect commented on frontend/controller/actions/group.js
> +          heading: L('Automatically switched to pledging {zero}', { zero: withGroupCurrency(0) }),
Having tested this out, I think from a UX perspective, it might make more sense to automatically show this prompt the user, instead of waiting for them to click on the notification, which they might miss, and then be confused about what's happening and why they're suddenly no longer a receiver.

What do you think?

2023-01-11 00:10 UTC, SebinSong commented on frontend/controller/actions/group.js
> +          heading: L('Automatically switched to pledging {zero}', { zero: withGroupCurrency(0) }),
@taoeffect I agree it makes more sense that way. Should we still keep the notification?

2023-01-11 00:38 UTC, taoeffect commented on frontend/controller/actions/group.js
> +          heading: L('Automatically switched to pledging {zero}', { zero: withGroupCurrency(0) }),
@SebinSong sure, let's keep the notification

2023-01-11 03:51 UTC, SebinSong commented
@taoeffect updated this PR with your request below

>  it might make more sense to automatically show this prompt the user, instead of waiting for them to click on the notification

2023-01-11 16:36 UTC, taoeffect requested changes
Forgot to regenerate the saved contracts using `grunt pin 0.0.12 --overwrite`

2023-01-11 21:38 UTC, taoeffect approved these changes
Great work @SebinSong! Approved!!

2023-01-11 21:38 UTC, merged