Use API_PORT and --port option instead of PORT_SHIFT
okTurtles/group-income pull request #1653
Opened 2023-06-15 15:23 UTC by snowteamer

Closes #1642

### Summary of changes:
- New `API_PORT` envar, allowing to specify the default backend port. If not defined, then port 8000 will be the default.
- New `--port` Grunt option, to be used in Grunt commands. Useful e.g. when running two or more server instances.
 Example: `grunt --port=8004` will try to launch a dev instance on port 8004, whereas the usual `grunt` command will rely on the `API_PORT` envar, or 8000 if not defined.
- Cypress tests have been updated to no longer refer to a hard-coded `http://localhost:8000 URL`.
  This allows to run them against a backend running on another port.

2023-06-20 23:21 UTC, Silver-IT approved these changes, later dismissed
Great work, @snowteamer. I totally approve this PR. :)

2023-06-20 23:21 UTC, Silver-IT commented on Gruntfile.js
> +}
It's a nice checking for exceptions.

2023-06-20 23:21 UTC, Silver-IT commented on frontend/views/pages/DesignSystem.vue
> +            link-to-copy.c-link(link='/app/join?groupId=21XWnNJvq9&secret=3763')
Nice fix.

2023-07-06 18:12 UTC, taoeffect approved these changes
LGTM! Just needs merge conflict fix.

2023-07-07 19:01 UTC, taoeffect requested changes
Marking as "changes requested" until merge conflict is fixed so that it correctly shows up in the list of PRs

2023-07-21 18:15 UTC, taoeffect approved these changes
Approved! Great work @snowteamer!!

2023-07-21 18:15 UTC, taoeffect commented on test/cypress/integration/group-paying.spec.js
> +const API_URL = Cypress.config('baseUrl')
Nice 👍

2023-07-21 18:15 UTC, merged