Issue 1629
okTurtles/group-income pull request #1655
Opened 2023-06-16 12:09 UTC by snowteamer

Closes #1629

### Summary of changes:
- New `process.env.CONTRACTS_VERSION`  field available, taken from `package.json`'s `contractsVersion`.
- The server will now send both its current `GI_VERSION` and `CONTRACTS_VERSION` to the client on every (re)connection, including in development mode, allowing it to reload if necessary (fix issue #1629).
- Fixed a bug causing the server to not log ping rounds despite the option being enabled.
-

2023-06-21 00:15 UTC, Silver-IT requested changes
Great work, @snowteamer. Left a few feedback.

2023-06-21 00:15 UTC, Silver-IT commented on backend/pubsub.js
> +      if (server.clients.size && server.options.logPingRounds) {
Nice catch. `server.clients` is `Set` object which has `size` instead of `length`.

2023-06-21 00:15 UTC, Silver-IT commented on frontend/controller/backend.js
> +sbp('okTurtles.events/on', NOTIFICATION_TYPE.UPDATE_AVAILABLE, (versionInfo) => {
I think it should be `NOTIFICATION_TYPE.VERSION_INFO` instead of `NOTIFICATION_TYPE.UPDATE_AVAILABLE`.

2023-06-21 00:15 UTC, Silver-IT commented on shared/domains/chelonia/chelonia.js
> +            sbp('okTurtles.events/emit', NOTIFICATION_TYPE.UPDATE_AVAILABLE, { ...msg.data })
I also think this should be `VERSION_INFO` instead of `UPDATE_AVAILABLE`.

2023-06-21 00:15 UTC, Silver-IT commented on frontend/controller/backend.js
> +sbp('okTurtles.events/on', NOTIFICATION_TYPE.UPDATE_AVAILABLE, (versionInfo) => {
Or should add `UPDATE_AVAILABLE` in `NOTIFICATION_TYPE`.

2023-06-26 15:54 UTC, snowteamer commented on shared/domains/chelonia/chelonia.js
> +            sbp('okTurtles.events/emit', NOTIFICATION_TYPE.UPDATE_AVAILABLE, { ...msg.data })
Yeah there was an inconsistency here, thank you for noticing!

2023-07-06 18:06 UTC, taoeffect approved these changes
Great work @snowteamer! Tested & approved!

2023-07-06 18:06 UTC, merged