Code reorganization + redesign + flow typecheck fixing + simplification
okTurtles/group-income pull request #166
Opened 2017-01-31 01:34 UTC by taoeffect

2017-01-31 01:35 UTC, taoeffect commented
Note:

- I will update the description of this PR once we have fixed the frontend tests not working on it

2017-01-31 18:00 UTC, vijayee commented on frontend/simple/js/database.js
> +    console.error(`addLogEntry: new entry hash bad parentHash: ${entry.parentHash}. Should be: ${last}. Entry:`, entry)
small typo, 'hash' should be 'has'

2017-01-31 20:09 UTC, vijayee requested changes

2017-01-31 20:09 UTC, vijayee commented on frontend/simple/js/state.js
> +  async saveState (
So I notice that we use saveState  on the action level but use saveSettings on the database level. Can we call it saveSettings on both since it does not persist the whole state object.

2017-01-31 20:09 UTC, vijayee commented on frontend/simple/views/EventLog.vue
> +          // return min
This looks like an old debug statement. Can you remove this.

2017-01-31 20:09 UTC, vijayee commented on frontend/simple/views/EventLog.vue
> +        let entry = makeEntry(ENTRY_TYPE.CREATION, group, null)
This portion of the code feels awkward to me. I think it should not be the place of the vue to manage the hashing of the object or the subscriptions. I think if  either process by which these processes change the vue should be unaffected. I think it would be better to handle this portion of the code in the actions or another layer. I'd imagine that ultimately the subscriptions would be managed by the loadState action and some groupCreation action.

2017-01-31 20:09 UTC, vijayee commented on shared/functions.js
> +    creationDate: 'now', // new Date().toISOString(),
I'm not sure what is going on with this change. Was this for debugging purposes?

2017-01-31 20:09 UTC, vijayee commented on shared/functions.js
>    primus.plugin('rooms', require('primus-rooms'))
Can we declare these dependencies at the top of the file?

2017-01-31 20:09 UTC, vijayee commented on shared/functions.js
> +    primus.save(require('path').join(__dirname, '../frontend/simple/assets/vendor/primus.js'))
Same here

2017-01-31 20:09 UTC, vijayee commented on shared/types.js
> +  creationDate: string;
I assume the plan is to use the date as a string?

2017-02-01 23:55 UTC, vijayee approved these changes

2017-02-02 00:00 UTC, merged