#1686 - Fix a few bugs in  payment-detail modal
okTurtles/group-income pull request #1688
Opened 2023-08-15 06:37 UTC by SebinSong

closes #1686

2023-08-15 06:55 UTC, SebinSong commented
Am going to get back to fixing the test failure in 24 hrs

2023-08-17 18:29 UTC, taoeffect requested changes
Excellent work @SebinSong! As far as I can tell all of the issues @snowteamer found have been addressed. 👏

However, I found one more issue that we should take the time to fix now: old sent payments from previous periods have a "Cancel payment" button:

![Screen Shot 2023-08-17 at 11 18 32 AM](https://github.com/okTurtles/group-income/assets/138706/f740a568-0f17-4152-9524-01dcaa447224)

![Screen Shot 2023-08-17 at 11 24 36 AM](https://github.com/okTurtles/group-income/assets/138706/573a2e35-4b7b-4f1d-b85c-808f4fd609b3)

This doesn't make sense to show for payments that have been completed and are in an older payment period than the current one.

So can we hide the button and the menu item in such cases?

2023-08-17 18:29 UTC, taoeffect commented on frontend/views/containers/payments/PaymentsMixin.js
> +      console.log(`@@ payments for the period [${period}]: `, payments)
Think this debug logging needs to be removed before we can merge, right?

2023-08-17 18:29 UTC, taoeffect commented on frontend/views/pages/Payments.vue
> +            // (context: https://github.com/okTurtles/group-income/issues/1686)
Thanks for adding this context in the comment 👍

2023-08-18 02:19 UTC, SebinSong commented
@taoeffect Updated the PR again with the work for your feedback.

2023-08-18 17:13 UTC, taoeffect approved these changes
Fantastic work @SebinSong! Approved!

2023-08-18 17:13 UTC, merged