Sebin/task/#1693 bug in user settings
okTurtles/group-income pull request #1698
Opened 2023-08-23 10:32 UTC by SebinSong

closes #1693

2023-08-23 10:35 UTC, SebinSong commented on frontend/views/components/tabs/TabWrapper.vue
> +      const fallbackLink = allTabNavLinks.find(item => item.url === 'my-account')
`fallbackLink` here is the case where the specified `tab` query doesn't match any tab items in the last. (e.g. `?modal=UserSettings&tab=asdfsadf`) we need to manually direct it to the `my-account` tab.

2023-08-23 10:51 UTC, SebinSong commented
@taoeffect 
As you pointed out, the cause of the issue is that two different vue components(`UserSettingsModal.vue` and `Payments.vue`) use the same query param `section`.
Manually resetting the value to `my-account` in `UserSettingsModal` did work but then I spotted another issue where the value of `section` in the url instantly gets reverted back to the value used by `Payments.vue` even when User-settings modal is working completely fine.
Turns out that's because we are opening the modal on top of `Payment.vue` page in this particular case which has a watcher for `$route` in it that updates the `section` query every time it detects a change.
So I decided to go for the hard way which is renaming `section` query to something else(`tab`) in UserSettings modal.

2023-08-24 17:35 UTC, taoeffect requested changes
Looking & working really great @SebinSong! Just one change request.

2023-08-24 17:35 UTC, taoeffect commented on frontend/views/components/tabs/TabWrapper.vue
> +      const fallbackLink = allTabNavLinks.find(item => item.url === 'my-account')
Good comment,  can you please add it as an in-line comment to the code? (In the future, all such comments are best added directly to the code instead of Github, so that they'll be remembered.)

2023-08-25 01:36 UTC, taoeffect approved these changes
Great work @SebinSong!

2023-08-25 01:36 UTC, merged