Fixed error to save scroll position
okTurtles/group-income pull request #1730
Opened 2023-09-19 08:25 UTC by Silver-IT

### Summary of Changes

- Closes #1711

2023-09-19 08:29 UTC, Silver-IT commented
@taoeffect, in order to work on the latest version of code regarding the chatroom, I have branched off on [this branch](https://github.com/okTurtles/group-income/tree/1697-remove-private-dms-group-dms-everywhere-and-use-directmessages-instead).
So I think this PR should be merged after the [PR #1709](https://github.com/okTurtles/group-income/pull/1709).

2023-09-23 00:41 UTC, taoeffect requested changes
Preliminary review

2023-09-23 00:41 UTC, taoeffect commented on frontend/model/contracts/identity.js
> +          },
Can you merge `e2e-protocol` back into this PR?

2023-10-06 17:15 UTC, taoeffect approved these changes
Seems to work! Great job @Silver-IT !

2023-10-06 17:15 UTC, merged