Updated login error message
okTurtles/group-income pull request #1731
Opened 2023-09-20 00:28 UTC by Silver-IT

Summary of Changes

- Closes #1727

2023-10-06 17:22 UTC, taoeffect requested changes
Nicely done, but some merge conflicts that need fixing + a request

2023-10-06 17:22 UTC, taoeffect commented on frontend/controller/actions/identity.js
> +        throw new GIErrorUIRuntimeError(L('Incorrect username or password'))
Please log the error here using `console.error`, e.g.:

```js
console.error('caught error calling retrieveSalt:', e)
```

2023-10-20 17:24 UTC, taoeffect approved these changes
Nicely done @Silver-IT! 👏

2023-10-20 17:24 UTC, merged

2023-10-20 19:03 UTC, taoeffect reviewed
~~Note: I had to undo this PR merge because it broke the flow after creating a group (no longer redirected to dashboard)~~

See: https://github.com/okTurtles/group-income/issues/1720#issuecomment-1773278280

2023-10-20 22:14 UTC, Silver-IT commented
I am on sure why this PR is related to [this error](https://github.com/okTurtles/group-income/issues/1720#issuecomment-1773278280), and why should be undone. I haven't made any changes except removing IIFE and adding try/catch.

I think that error is related to any other stuff. Maybe related to login process.