#1742 Use 'submit-button' component for asynchronous actions
okTurtles/group-income pull request #1750
Opened 2023-10-04 07:46 UTC by SebinSong

closes #1742

2023-10-04 14:05 UTC, SebinSong commented on frontend/views/components/UsersSelector.vue
> +      i18n Create
In order to use a `button-submit` component, had to pass an async method as the click handler (otherwise it leads to a Vue console warning requiring it). That is why I created/passed an async submitHandler here instead of emitting a 'submit' event.

2023-10-04 14:06 UTC, SebinSong commented on frontend/views/containers/chatroom/ChatMembersAllModal.vue
> +                i18n(:args='LTags("span")') Add {span_} to channel{_span}
wasn't quite sure about why span_` and `_span` are used here but just left it as is for now.

2023-10-04 16:03 UTC, taoeffect requested changes
Nicely done @SebinSong! Left a few comments.

Also, when creating a DM and clicking the button here really quickly with the mouse:

![Screenshot 2023-10-04 at 9 02 21 AM](https://github.com/okTurtles/group-income/assets/138706/56e20b0e-111e-49ad-b2a9-bfc6f02826a2)

I see these errors appear in the console:

![Screenshot 2023-10-04 at 9 02 02 AM](https://github.com/okTurtles/group-income/assets/138706/932eb7f0-7080-4d68-b5b2-e566af1f96e3)

2023-10-04 16:03 UTC, taoeffect commented on frontend/views/containers/user-settings/UserProfile.vue
> +          // TODO: once account-deletion is implemented, replace this with submit-button component to take care of the async process.
In the comment, can you rename `submit-button` to `ButtonSubmit.vue`? It makes it clearer, at least to me, which component is being discussed.

2023-10-04 16:03 UTC, taoeffect commented on frontend/views/containers/payments/SendThankYouModal.vue
> +        await sbp('gi.actions/group/sendPaymentThankYou', {
Good catch! Can you please also:

1. wrap the user-facing error message below with an `L` function
2. Add above line 102: `console.error('SendThankYouModal caught:', err)`

2023-10-05 08:13 UTC, SebinSong commented on frontend/views/containers/user-settings/UserProfile.vue
> +          // TODO: once account-deletion is implemented, replace this with submit-button component to take care of the async process.
done!

2023-10-05 08:13 UTC, SebinSong commented on frontend/views/containers/payments/SendThankYouModal.vue
> +        await sbp('gi.actions/group/sendPaymentThankYou', {
done!

2023-10-05 08:18 UTC, SebinSong commented
@taoeffect Updated the PR again with the work for your feedbacks.

Regarding the console errors you pointed out, they are caused by Vue failing to anchor a `ref` to `ModalBaseTemplate.vue` because its root element is not an HTML element but a built-in Vue component (`<transition />`)
So I updated the `closeModal` method so that it emits `CLOSE_MODAL` event directly from within there, which clears those errors.

2023-10-05 16:21 UTC, taoeffect approved these changes
Great work!!!

2023-10-05 16:21 UTC, merged