#1558 - markdown in chat
okTurtles/group-income pull request #1815
Opened 2024-01-18 06:24 UTC by SebinSong

work on #1558

This PR is the work for allowing below list of styled markdowns to be displayed in the chat message.
**1.** Code inline
**2.** Code block
**3.** Italic
**4.** Bold
**5.** Unordered list
**6.** Strikethrough
**7.** Link tag

[ screenshots ]

<img src='https://github.com/okTurtles/group-income/assets/17641213/b5883aba-542d-479f-9760-ba617552aba5' width='560'>

The colours of them are arbitrarily chosen by me (e.g. `<code>abc</code>` is in orange color) but let me know if we want to update them to different ones.

I've also worked on adding this various call-to-action buttons for some of the styles, which can make the menu start to look a bit crowded now, but let me know if we don't want this buttons.

<img src='https://github.com/okTurtles/group-income/assets/17641213/117ff33c-3bb9-4974-8f4c-1dbb93ab7040' width='360'>

2024-01-18 17:02 UTC, taoeffect requested changes
Fantastic work @SebinSong! 🥇 

This is looking really solid.

Here are the only issues I could find:

#### 1. spacing on adjacent styled words

Notice that whenever adjacent words have styling on them, it looks like they're part of the same word:

![Screenshot 2024-01-18 at 8 46 11 AM](https://github.com/okTurtles/group-income/assets/138706/e154f897-49a3-4c62-9305-53ef6884de0e)

Compare that with the spacing that Slack adds between adjacent words with styling.

#### 2. not using real markdown

This is my fault, as I forgot to say that we shouldn't use Slack's syntax for styling.

Slack doesn't actually use real markdown, it uses its own modified version of markdown. In most markdown renderers that I know, and in the official specs,\*asdf\* gets rendered as *asdf*, not **asdf**.

Let's avoid propagating Slack's confusion any further, and conform to the official markdown spec.

#### 3. fix combined styling issues

In a lot of the examples i show in the above screenshot, whenever styling is combined with other styling, the results are wrong.

For example, ***bold italic*** didn't get rendered properly. `~*_strikethrough_*~` didn't get rendered properly (note: with the fixed markdown, it would be `~**_strikethrough_**~`).

Similarly, need to make sure that styling with links renders properly.

#### 4. Move the non-styling buttons to the right

Now that we've got more buttons, I think it makes sense to organize them a bit better. Since styling is a more commonly used activity than some of the special buttons that we already have, we can move those special buttons over to the right:

![Screenshot 2024-01-18 at 8 59 58 AM](https://github.com/okTurtles/group-income/assets/138706/f22b7f3c-81e1-4d7f-8e9a-220e0a12c07c)

I would also preserve a tiny bit of margin between the "send" button and the special buttons so that the send button is not accidentally tapped on mobile devices.

2024-01-18 17:02 UTC, taoeffect commented on marked-test.js
> +// !!! TODO: REMOVE THIS FILE AFTER DEVELOPEMENT !!!
Should this file be removed now?

2024-01-23 02:59 UTC, SebinSong commented
@taoeffect 
Just updated the PR with the work for your feedbacks. let me attach the demo for a couple of your feedback items too.

![image](https://github.com/okTurtles/group-income/assets/17641213/a1a33be6-a1a8-4d4a-9b77-0dd11122382b)

2024-01-23 19:09 UTC, taoeffect requested changes
Fantastic work @SebinSong! 💪 

I think this will be the final change request before merging:

1. Can you avoid changing the font color for *italic* and ***bold italic*** text?
2. Can you use the existing blue color that we use for links for links?
3. I think I found an issue with blockquotes:

![Screenshot 2024-01-23 at 11 07 47 AM](https://github.com/okTurtles/group-income/assets/138706/3cec56e2-0aff-42cd-8a38-0634cd0eea09)

There was supposed to be an empty line in the blockquote:

![Screenshot 2024-01-23 at 11 08 06 AM](https://github.com/okTurtles/group-income/assets/138706/762a6b31-0609-4a78-8d57-17c14c16e9df)

E.g.:

> test
> test
> test
> 
> test

Not:

> test
> test
> test
> test

2024-01-23 23:41 UTC, SebinSong commented
@taoeffect updated PR according to your feedbacks

<img src='https://github.com/okTurtles/group-income/assets/17641213/e775f551-1c97-4d2a-9cd8-77246b1934be' width='380'>

2024-01-23 23:54 UTC, taoeffect approved these changes
🎉 🎉 🎉 

Approved!! 😄

2024-01-23 23:54 UTC, merged