Fix #1861
okTurtles/group-income pull request #1888
Opened 2024-03-14 11:08 UTC by corrideat

2024-03-14 11:38 UTC, taoeffect requested changes
Review ready!

2024-03-14 11:38 UTC, taoeffect commented on frontend/model/contracts/chatroom.js
> +          console.warn('[gi.contracts/chatroom/join/sideEffect] Error at sideEffect', e?.message || e)
There are a lot of errors that got converted to warnings that are unrelated to calls to publishEvent in this PR.

Ideally we keep most of the errors as errors, and underfit - in other words, it'd be better to have more errors logged as errors in the console, than missing errors we might want to be aware of.

Ideally this PR only changes a couple of lines related to publishEvent that are regularly logged as errors that happen due to expected circumstances.

2024-03-15 09:37 UTC, corrideat commented
Instead of using `setTimeout` / `setInterval`, I'd refactor this as follows

```js
const foo = () => {
  sbp('chelonia/contract/wait', contractIDs, () => {
    if (currentUserHasChanged) return; // alternatively, you could use an event listener
    if (contractIDsInQueue) { // the check that you're doing
      foo()
      return
    }
    // The rest of the logic follows here
  }).catch(/* ... */);
}
```

I think this would be safe (or safer) while avoiding unnecessary checking. It also checks for the user changing, which is needed because you don't want to remove contracts in that case. Maybe you can also give up after a certain number of attempts.

2024-03-15 11:03 UTC, taoeffect approved these changes
👍

2024-03-15 11:03 UTC, merged