Improve the performance of Chat page
okTurtles/group-income pull request #1904
Opened 2024-04-03 06:50 UTC by Silver-IT

### Summary of Changes

- Closes #1897 
- Fix error to display text in notification (When there is mentions inside the text)

2024-04-03 07:23 UTC, Silver-IT reviewed
Ready for the review!

2024-04-03 10:03 UTC, taoeffect requested changes
Nice work @Silver-IT! It does seem a bit smoother. 😎 👍 

While reviewing this PR, I found a few issues, and while they might not be related to this PR specifically, I'm wondering if you can still address them in this PR?

### 1. Scrolling behavior broken

When new messages are added to a chatroom, and someone was scrolled all the way to the bottom, they do not continue scrolling downward to see the new messages as they should:

https://github.com/okTurtles/group-income/assets/138706/06116699-558b-407e-b5fd-d85b5adc3181

### 2. Extraneous error logging

There is a rogue `console.error`:

![Screenshot 2024-04-03 at 6 42 36 PM](https://github.com/okTurtles/group-income/assets/138706/e3fab170-fa2a-477c-8960-198babe81e68)

Resulting in console errors like this depending on how the chatroom views are accessed:

![Screenshot 2024-04-03 at 6 43 52 PM](https://github.com/okTurtles/group-income/assets/138706/4c4e8958-d81c-414c-979a-b4df022b8511)
![Screenshot 2024-04-03 at 6 42 31 PM](https://github.com/okTurtles/group-income/assets/138706/226cc75c-872e-4b8c-a01b-261567aa5db8)

2024-04-03 10:04 UTC, taoeffect commented on frontend/views/containers/chatroom/ChatMain.vue
> +            state = await sbp('chelonia/in/processMessage', event, state)
@corrideat could you review these changes?

2024-04-03 11:00 UTC, Silver-IT commented
> Scrolling behavior broken

I remember this is what we discussed very long ago. That scroll works wrong only when using Multi Container Firefox addon. When you open two browsers(not using Multi Container Addon), and test, it would work fine as expected.

2024-04-04 08:12 UTC, corrideat commented on frontend/views/containers/chatroom/ChatMain.vue
> +            state = await sbp('chelonia/in/processMessage', event, state)
This seems to be fine, although I'd keep the check for contract ID changes so that processing messages can be stopped if no longer needed

2024-04-04 10:25 UTC, taoeffect approved these changes
Nice!

2024-04-04 10:25 UTC, merged