#1947 - Channel links in chat
okTurtles/group-income pull request #1976
Opened 2024-04-29 22:21 UTC by SebinSong

closes #1947 

implementing various Channel-Link related UI elements which are in below.

**1] Active channel links & Auto-completion menu for channel mentions**

<img src='https://github.com/okTurtles/group-income/assets/17641213/ed22c4cd-4458-4d24-bb1d-201e379ac7f0' width='450'>

**2] A private channel is not clickable to someone who has not been invited**

<img src='https://github.com/okTurtles/group-income/assets/17641213/7a0d4eab-dcd4-449c-8c1a-ea606067de2d' width='450'>

2024-04-30 16:59 UTC, taoeffect submitted a review, later dismissed
@SebinSong You did an amazing job on this PR!

I'm really quite impressed with this PR. It's a rather large PR, yet perfectly addresses the issue, and no matter how hard I tried, I couldn't find any bug in it.

I'm especially impressed with how you even got it to work where, when someone posts a link to a private chatroom and someone hasn't joined, it is grey, but then when they are added to the room, it becomes blue and clickable. 👏 

I could merge it as-is right now.

Or, if you'd like to make a couple of small changes to it now (instead of in a separate PR), I can wait.

One change is a request for a comment, and the other is related to a boyscoutting issue related to the "Channel Description" button when viewing a channel you haven't yet joined:

![Screenshot 2024-04-30 at 9 43 19 AM](https://github.com/okTurtles/group-income/assets/138706/5796ab66-a201-4383-990f-a88f66a64044)

This button currently does nothing. I think it wouldn't be very professional to release the app with it. I also don't know what it's even supposed to do, so I updated [the Figma designs](https://www.figma.com/file/mxGadAHfkWH6qApebQvcdN/Group-Income-2.0?type=design&node-id=23766%3A267514&mode=design&t=lRcnO92ItfsTXBBo-1) to make it just say "Details", same as Slack.

However, I think we don't really need this button right now. So another simple change this PR could do would be to just hide this button entirely. What do you think, is that something that can be done for this PR?

2024-04-30 16:59 UTC, taoeffect commented on frontend/views/containers/chatroom/CreateNewChannelModal.vue
> +    }
This same substitution is needed here too? 🤔 

Do you happen to know why? If so, could you add a comment explaining why it's also necessary here?

2024-04-30 21:05 UTC, SebinSong commented on frontend/views/containers/chatroom/CreateNewChannelModal.vue
> +    }
@taoeffect No, This is something I forgot to delete actually. good catch.

2024-04-30 21:39 UTC, SebinSong commented
thanks @taoeffect. I removed that 'channel description' button.

2024-05-01 01:09 UTC, taoeffect requested changes
Perhaps removing some of that code wasn't the right thing to do...

![Screenshot 2024-04-30 at 6 08 23 PM](https://github.com/okTurtles/group-income/assets/138706/a7ce7be8-c10d-46aa-ad78-d34eaadea47d)

Maybe the other code needed to be removed?

Or if both are needed, can you add a comment explaining why? (If you know)

2024-05-02 08:37 UTC, SebinSong commented
@taoeffect
Updated the PR with the fix.
Turns out the watcher was needed. the name field is bound to the component state via `v-model` so putting things in an `input` event handler didn't work.

2024-05-02 15:26 UTC, taoeffect approved these changes
Beautiful done @SebinSong !

2024-05-02 15:27 UTC, merged