Sebin/task/#1934 chat format buttons on mobile
okTurtles/group-income pull request #1999
Opened 2024-05-18 19:15 UTC by SebinSong

work on **problem 1. & 2.** of the issue #1934 

@taoeffect 
for the **problem 1.** , I actually went a bit ambitious and increased the buttom padding to `1.25rem` but please let me know if you feel it's too much.

<img src='https://github.com/okTurtles/group-income/assets/17641213/4af82efc-a280-44fd-8732-2cba3d40a3d1' width='430'>

And as a fix for the **problem 2.** , the target text segment now remains selected after pressing the format buttons.

2024-05-19 16:53 UTC, taoeffect requested changes
Nicely done @SebinSong! This seems much improved.

One issue I noticed is that when toggling the formatting, the formatting icon remains blue instead of toggling on and off.

E.g. highlight some text, press the italic icon, and press it again. It will remain highlighted in blue instead of toggling itself off and on.

Note: I tested this on my phone using `grunt dev --tunnel`

2024-05-20 00:12 UTC, SebinSong commented
@taoeffect 
Whether the format button is highlighted or not doesn't mean that it's toggled on/off. It's that the button remains focused after clicking the button. I will make a fix where it blurs after the text transformation (just like how those buttons in text editors of the Github work)

<img src='https://github.com/okTurtles/group-income/assets/17641213/9a522692-1896-4e15-87f7-b5a65346558e' width='420'>

2024-05-20 02:33 UTC, taoeffect requested changes
![tmp-1716172239537](https://github.com/okTurtles/group-income/assets/138706/27fb2b79-a73c-409c-aa6f-b85dce6f6454)

@SebinSong please give this a try on your end using `grunt dev --tunnel`. I tried the latest changes on my phone and there were still a few problems:

- The latest changes didn't seem to do anything, the blue icon remained blue after being tapped
- It's still really hard to tap the icon while text is highlighted when the lighted text is right above the icon. Sometimes Android still gets confused doesn't realize you're trying to press the icon and instead thinks you're messing with the selection
- Additionally, the white hover bubble appears above the button, e.g. in this case "Strikethrough", covering and hiding the text that's being modified so that the user doesn't really have any idea what's happening / how the text is being modified. Perhaps the best way to deal with this is to just not show it on mobile.

2024-05-21 02:11 UTC, taoeffect approved these changes
Nicely done!

2024-05-21 02:11 UTC, merged