Display app version as well as contracts version
okTurtles/group-income pull request #2094
Opened 2024-06-19 07:05 UTC by Silver-IT

### Summary of Changes

- Closes #2081

2024-06-19 17:32 UTC, taoeffect requested changes
Nicely done! One minor change request for simplifying the string for translators:

2024-06-19 17:32 UTC, taoeffect commented on frontend/views/components/tabs/TabWrapper.vue
> +          ...LTags('span'),
Is there a reason for this `span` tag?

I tried changing this to: `App Version: {appVersion}{br_}Contracts Version: {contractsVersion}`

And it worked just fine:

![Screenshot 2024-06-19 at 10 31 53 AM](https://github.com/okTurtles/group-income/assets/138706/51c6a163-a5ef-4916-b5f9-ad8a13af1c6d)

2024-06-19 21:41 UTC, Silver-IT reviewed
Review ready!

2024-06-20 03:20 UTC, taoeffect approved these changes
🫡

2024-06-20 03:20 UTC, merged