Make income details update notification consistent across user account
okTurtles/group-income pull request #2100
Opened 2024-06-20 21:41 UTC by Silver-IT

### Summary of Changes

- Closes #2056

2024-06-20 22:30 UTC, Silver-IT reviewed
Ready for the review!

2024-06-25 18:23 UTC, taoeffect requested changes
Great work @Silver-IT! This is quite a PR!

I left a few change requests.

Also I tested this with mobile (using `grunt dev --tunnel`) and it seemed to work correctly (when I dismissed the banner on desktop, it also dismissed it on the phone).

However, when I ran this command on desktop to try and get the banner to re-show, it didn't work:

```js
sbp('gi.actions/kv/updateDistributionBannerVisibility', { contractID: sbp('state/vuex/state').currentGroupId, hidden: false })
```

Why is that?

Also, could you please merge `master` into this PR so that this error goes away?

![Screenshot 2024-06-25 at 11 04 06 AM](https://github.com/okTurtles/group-income/assets/138706/7b7a1019-88f5-461c-b2b1-8c039ff18a99)

2024-06-25 18:23 UTC, taoeffect commented on frontend/controller/actions/identity.js
> +        await sbp('gi.actions/kv/loadPreferences')
Would it be OK to move this up next to the other `kv/load` statement on line 398?

2024-06-25 18:23 UTC, taoeffect commented on frontend/controller/actions/kv-stores.js
> +'use strict'
Nice job splitting these out into a new file! I agree they belong in a separate file.

Could you please make it even more organized by creating separate scoped files? 

For example, for each KV store that you create, a separate file:

E.g. `group-kv.js` (all group contract related KV selectors go here), and `identity-kv.js` (all identity contract related selectors go here).

Also, I think we should include the name of the type of contract in the selector itself to make things even more clear, so e.g.:

```
'gi.actions/kv/fetchChatRoomUnreadMessages'
```

Would get renamed to:

```
'gi.actions/identity/kv/fetchChatRoomUnreadMessages'
```

And:

```
'gi.actions/kv/updateLastLoggedIn'
```

Would get renamed to:

```
'gi.actions/group/kv/updateLastLoggedIn'
```

This makes it super clear which KV store is being dealt with.

2024-06-25 18:23 UTC, taoeffect commented on frontend/controller/actions/identity.js
> +  ].map(fnName => [`gi.actions/identity/${fnName}`, (...args) => sbp(`gi.actions/kv/${fnName}`, args)])),
I appreciate that you did this. The thing is, it turns out that the problems on the server were related to real bugs in the internals/core of Chelonia, and we're gonna have to recreate the group anyway, so now is a good time to organize these selectors.

Please feel free to delete this section and refactor the selectors as needed. Also, please see my comment below about organizing into `identity-kv.js` etc. type files.

2024-06-26 02:14 UTC, Silver-IT commented on frontend/controller/actions/identity.js
> +        await sbp('gi.actions/kv/loadPreferences')
Yeah, it's fine.

2024-06-26 02:16 UTC, Silver-IT commented on frontend/controller/actions/kv-stores.js
> +'use strict'
Makes sense. Nice suggestion!

2024-06-26 02:37 UTC, Silver-IT commented
> However, when I ran this command on desktop to try and get the banner to re-show, it didn't work:
> ```
> sbp('gi.actions/kv/updateDistributionBannerVisibility', { contractID: sbp('state/vuex/state').currentGroupId, hidden: false })
> ```
> Why is that?

I can't understand why it doesn't work. Actually, it works well on my side.

2024-06-26 18:30 UTC, taoeffect commented on frontend/model/state.js
> +  preferences: {}
Any time we modify the state like this we need to add an entry in `postUpgradeVerification`

2024-06-26 18:45 UTC, taoeffect approved these changes
I hope it's OK with you that I added the `postUpgradeVerification` fix to get this merged! Great job @Silver-IT !

2024-06-26 18:45 UTC, merged