Fix issue with ephemeral reference count
okTurtles/group-income pull request #2154
Opened 2024-07-04 20:22 UTC by corrideat

2024-07-04 23:12 UTC, Silver-IT requested changes
Nice work, @corrideat!

I can see the changes of this PR is to wait `gi.actions/identity/kv/deleteChatRoomUnreadMessages`, and I made one question.

2024-07-04 23:12 UTC, Silver-IT commented on frontend/model/contracts/shared/functions.js
> +  await sbp('gi.actions/identity/kv/deleteChatRoomUnreadMessages', { contractID })
Why do we need to wait this KV action? It's to save unreadMessages in identityContractID space, not chatRoomID space.

2024-07-05 01:22 UTC, corrideat commented on frontend/model/contracts/shared/functions.js
> +  await sbp('gi.actions/identity/kv/deleteChatRoomUnreadMessages', { contractID })
In that case, you're right that waiting shouldn't be needed.

2024-07-05 12:59 UTC, Silver-IT submitted a review, later dismissed
Nice work, @corrideat!

2024-07-05 18:36 UTC, taoeffect approved these changes
Probably OK

2024-07-05 18:36 UTC, merged