#2140 - Set reasonable character limit for user bio
okTurtles/group-income pull request #2175
Opened 2024-07-09 22:09 UTC by SebinSong

closes #2140 

<img src='https://github.com/okTurtles/group-income/assets/17641213/c72f7fc7-a536-4d57-a1fd-4156bbf328d7' width='430'>

While at it, I actually added & DRYed the same UI to some other places too. (e.g. below modal)

<img src='https://github.com/okTurtles/group-income/assets/17641213/c3fce69e-e51b-4270-9627-09633242c302' width='430'>

2024-07-09 22:15 UTC, taoeffect requested changes
Great work @SebinSong!

In most projects these sorts of checks are done on both the frontend (which can be bypassed easily) and the backend (which is hard to bypass). Our equivalent of the "backend" are the contracts. Similar to how other PRs handled this, could you update the contract validation functions to check for these limits too?

2024-07-09 23:24 UTC, SebinSong commented
Updated

2024-07-10 01:50 UTC, taoeffect commented on frontend/model/contracts/group.js
> +        if (data?.description.length > CHATROOM_DESCRIPTION_LIMITS_IN_CHARS) {
This `data?` is unnecessary because `data` shouldn't be `null` (the previous check will throw if it is null).

2024-07-10 02:07 UTC, taoeffect approved these changes
Approved! Fantastic work @SebinSong!

2024-07-10 02:07 UTC, merged