#2218 - Set upper limit for group pledge amount
okTurtles/group-income pull request #2224
Opened 2024-07-18 20:56 UTC by SebinSong

closes #2218 

<img src='https://github.com/user-attachments/assets/22f6423f-2d95-4cd6-8cec-97c9af5f6b1e' width='520'>

2024-07-18 21:01 UTC, taoeffect requested changes
Great work @SebinSong! A couple of change requests:

2024-07-18 21:01 UTC, taoeffect commented on frontend/model/contracts/misc/flowTyper.js
> +    number(value, _scope)
Please re-use the return value of `number` (like `stringMax` does)

2024-07-18 21:01 UTC, taoeffect commented on frontend/model/contracts/shared/constants.js
> +export const GROUP_MAX_PLEDGE_AMOUNT_STRING = '1,000,000,000$'
The `$` should be in front. But nevermind that, this constant shouldn't be here at all, please use the getter `withGroupCurrency` instead.

2024-07-18 23:02 UTC, taoeffect reviewed
The way this PR is implemented, the error doesn't appear immediately, but only when you click "Save":

![Screenshot 2024-07-18 at 4 01 17 PM](https://github.com/user-attachments/assets/366cc64e-b5f3-4c18-9431-456f23883951)

Is there a way to get it to be validated immediately as well, like when letters are added?

![Screenshot 2024-07-18 at 4 00 45 PM](https://github.com/user-attachments/assets/b6445928-11fd-4f71-bdf4-5652e05be080)

2024-07-19 02:11 UTC, SebinSong commented on frontend/views/containers/access/SignupForm.vue
> +        this.$refs.formMsg?.danger(e.message)
boy-scouting the console error occurring during sign-up.

2024-07-19 04:03 UTC, taoeffect approved these changes
Fantastic!

2024-07-19 04:03 UTC, merged