#2233 - Custom PWA installation in Home.vue
okTurtles/group-income pull request #2242
Opened 2024-07-20 06:13 UTC by SebinSong

closes #2233 

@taoeffect 
First of all, be aware that this implementation is based on [this MDC article](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Trigger_install_prompt), which states below warning:

> Warning: The technique described here depends on the [beforeinstallprompt](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeinstallprompt_event) event, which is non-standard and currently only implemented in Chromium-based browsers.

Both Safari desktop/iOS don't support([reference](https://caniuse.com/?search=beforeinstallprompt)) / fire **'beforeinstallprompt'** event, so the logic won't apply to them.
 
Below are some proof screenshots that it worked on my Android chrome when tried with `grunt dev --tunnel`

 [ Chrome Android ]
 
![KakaoTalk_Photo_2024-07-20-17-59-24 002](https://github.com/user-attachments/assets/5f6ad3c9-5407-4696-9971-a88021168bca)

![KakaoTalk_Photo_2024-07-20-17-59-23 001](https://github.com/user-attachments/assets/933b70f4-b40b-4d03-a7d4-e0039c4a3bc4)

 [ Chrome desktop ]
 
 
![image](https://github.com/user-attachments/assets/4efa3a35-0db1-4594-b1a1-d57ae7e77b5f)

2024-07-20 19:47 UTC, taoeffect requested changes
Awesome work @SebinSong!

Oddly enough I wasn't able to get this to appear in Brave, although that's good (can you make sure it doesn't appear on Desktop browsers?).

Some change requests/adjustments:

- Could you move the box downward so that it's about 30 px from the bottom of the screen?
- Could you adjust the colors so that instead of blue on a dark background, it's more of a different shade of grey when in dark mode?
- Could you also make sure it looks good in light mode too?

I'll test this on mobile when I have time (preparing a talk right now)

2024-07-22 10:43 UTC, SebinSong commented
@taoeffect Updated the PR again

**[ Light ]**

<img width="314" alt="light" src="https://github.com/user-attachments/assets/c1e35a83-4db2-48f7-9e96-e081e5f9f98b">

**[ Dark ]**

<img width="317" alt="dark" src="https://github.com/user-attachments/assets/ecc7a562-4ef3-4bb1-b484-e98bcc687c1e">

2024-07-22 10:46 UTC, SebinSong commented on frontend/views/pages/Home.vue
> +  banner-simple.hide-hoverable-device.hide-tablet.c-pwa-promo(
`.hide-hoverable-device.hide-tablet` ensures that this banner won't show in desktop.

2024-07-25 21:14 UTC, taoeffect approved these changes
Nice work @SebinSong!

2024-07-25 21:14 UTC, merged