#2002 allow DM to yourself
okTurtles/group-income pull request #2343
Opened 2024-09-10 21:19 UTC by SebinSong

closes #2002

2024-09-10 21:26 UTC, SebinSong commented on frontend/views/components/UsersSelector.vue
> -      this.clear()
Apparently `usernames` here was meant to be removed in [this previous commit](https://github.com/okTurtles/group-income/commit/f8cac6630b098bf693585db3fd23a60b5a9977a7) but went unnoticed, causing a run-time error. So removed it here.

2024-09-10 21:31 UTC, SebinSong commented
@taoeffect 
Let me know if you feel that a test-step for creating a DM to myself should be added to `group-chat-direct-message.spec.js`.

2024-09-11 01:10 UTC, taoeffect reviewed
Nice work @SebinSong, preliminary / partial review and one question:

2024-09-11 01:10 UTC, taoeffect commented on frontend/controller/actions/identity.js
> +      .map(memberID => rootGetters.ourContactProfilesById[memberID].contractID)
Why is this change being made? I don't quite understand the reason for filtering out our own contract even if it's intentionally specified.

2024-09-11 01:18 UTC, taoeffect requested changes
I don't know if this is an issue with this PR or something that went unnoticed.

1. I created a group and invited u2 and u3.
2. u2 created a DM with u1
3. u1 then added u3  to that DM:

![Screenshot 2024-09-10 at 6 17 10 PM](https://github.com/user-attachments/assets/bdb3d826-c9ca-4b1f-8dc5-46a3b42cfd31)

And now for u1 there's a DM with u2 and u3, but the user icon is grey:

![Screenshot 2024-09-10 at 6 16 57 PM](https://github.com/user-attachments/assets/4bc8261c-f42b-48d6-9492-288a5761511b)

2024-09-11 03:42 UTC, SebinSong commented on frontend/controller/actions/identity.js
> +      .map(memberID => rootGetters.ourContactProfilesById[memberID].contractID)
`partnerIDs` here is used to call sbp(`gi.actions/chatroom/join`) further down the logic [2], which is called by default for the DM creator [1].

```js
    await sbp('gi.actions/chatroom/join', { ... }) [1]

    for (const partnerID of partnerIDs) {
      await sbp('gi.actions/chatroom/join', { ... }) [2]
    }
```

Now that we expose the current user in this 'create new DM' modal list, there is cases where the members contain the current user too. This case needed to be taken account here.

<img width="480" alt="me-in-other" src="https://github.com/user-attachments/assets/199d51b0-7a91-498b-ae06-98cbb8431edc">

2024-09-11 03:43 UTC, SebinSong commented
@taoeffect Fixed the typo that caused that greyed-out photo issue. it does show now.

<img src='https://github.com/user-attachments/assets/f5e7ab7c-33f8-435d-96e3-e70a2fd12045' width='450'>

2024-09-12 17:20 UTC, taoeffect approved these changes
Excellent job @SebinSong! 👏

2024-09-12 17:20 UTC, merged