#2445 - add Download/Delete buttons and display image size in the image viewer
okTurtles/group-income pull request #2453
Opened 2024-12-10 10:51 UTC by SebinSong

closes #2445 

**[screenshot]**

<img width="380" src="https://github.com/user-attachments/assets/e630ac0a-b8e8-43d8-8362-3d32979913ae">

**[screenshot in forced-color mode]**

<img width="380" src="https://github.com/user-attachments/assets/1815965f-0d15-47b8-8cf9-b710b278fe50">

---
The issue was that these functionalities are not available on mobile but I thought they are good additions for desktop size screen too and so made them available for both.

Thanks,

2024-12-10 22:17 UTC, taoeffect requested changes
Seems to work really well!

Fantastic work @SebinSong! One minor issue found.

2024-12-10 22:17 UTC, taoeffect commented on frontend/views/containers/chatroom/file-attachment/ChatAttachmentPreview.vue
> +      console.log('!@# attachment list: ', this.attachmentList)
Stray debugging

2024-12-10 23:57 UTC, SebinSong commented
@taoeffect Updated the PR again.

2024-12-11 23:06 UTC, SebinSong commented
@taoeffect I think this issue has been resolved by [this](https://github.com/okTurtles/group-income/pull/2357) recently merged PR and we can discard this PR.

2024-12-12 00:18 UTC, SebinSong commented
@taoeffect as reported in [this Slack thread](https://okturtles.slack.com/archives/C02QF71TK1Q/p1733961421987199), upload-image functionality is currently broken in `master`. Pls don't review this PR until this is resolved.

2024-12-12 11:09 UTC, SebinSong commented
@taoeffect Apparently, the broken image upload functionality requires us to refactor the entire image compression logic. Let me make this fix as part of this PR and let you know if it's ready for review again.

2024-12-18 11:42 UTC, SebinSong commented
@taoeffect This PR is ready for review again.

2024-12-18 17:31 UTC, taoeffect approved these changes
Brilliant!

2024-12-18 17:31 UTC, merged