Improved Docker support (Closes #375) + bumped some dependencies
okTurtles/group-income pull request #379
Opened 2018-04-16 00:21 UTC by taoeffect

+ Greatly improved docker support & docs (#375)
+ Updated dependencies: sqlite3, grunt-exec, grunt-sass
+ Fixed [stylelint errors](https://github.com/okTurtles/group-income-simple/pull/370#issuecomment-381438966) that I encountered in PR #370

EDIT:

+ Also, this might close issue #378 (running two GIS instances at the same time)

### How to run two GIS instances

You have to have **two** cloned directories of `group-income-simple`, and both of them have to have the changes in this PR.

Then in one terminal window:

```
$[terminal-1] cd path/to/first/group-income-simple
$[terminal-1] grunt dev    # or npm run docker
```

Then in another terminal window:

```
$[terminal-2] cd path/to/second/group-income-simple
$[terminal-2] PORT_SHIFT=1 grunt dev    # or PORT_SHIFT=1 npm run docker
```

Now in one browser window you visit http://localhost:8000, and in another window (either an incognito window, or a different browser, or a different firefox container tab), visit http://localhost:8001

2018-04-16 00:50 UTC, taoeffect commented
Note: I just pushed some changes to this PR to potentially close issue #378 as well (ability to run two different GIS instances), as it required updating the docker stuff to in order to do that, I decided it made sense to do both in 1 PR.

2018-04-16 13:09 UTC, sandrina-p requested changes
On my machine it still throws the same error when I run `PORT_SHIFT=1 grunt dev`
```
Running "connect:dev" (connect) task
Started connect web server on http://localhost:8001

Running "backend:relaunch" task
backend: forking...

Running "watch" task
Waiting...
Fatal error: Port 35729 is already in use by another process.
```

2018-04-16 13:09 UTC, sandrina-p commented on .Gruntfile.babel.js
> +      stylelint: './node_modules/.bin/stylelint "frontend/simple/**/*.{css,scss,vue}, !frontend/simple/js/ignored/**"',
What's this path? I think this path only exists at your machine because that path doesn't exist remotely nor my machine

2018-04-16 23:56 UTC, taoeffect commented
@sandrina-p My latest changes should fix all the issues you encountered (hopefully) :)

2018-04-17 18:39 UTC, sandrina-p approved these changes
Everything works fine now! 🎉

2018-04-17 18:41 UTC, merged