Added donation buttons & links.
okTurtles/group-income pull request #468
Opened 2018-08-07 06:18 UTC by dotmacro

Closes #332

2018-08-07 18:32 UTC, sandrina-p approved these changes

2018-09-07 23:25 UTC, taoeffect commented on README.md
> +[![Bitcoin](https://img.shields.io/badge/donate-BTC-blue.svg)](https://okturtles.org/donate/) [![ETH](https://img.shields.io/badge/donate-ETH-blue.svg)](https://okturtles.org/donate/) [![Litecoin](ht
Lets just have a single donate button here with `Donate` in the grey section and ❤️ in the blue section?

2018-09-07 23:26 UTC, taoeffect commented on README.md
> +Donations to [support development on Group Income](https://groupincome.org/donate/) and the [other work of the okTurtles Foundation](https://okturtles.org/donate/) are greatly appreciated.
Just one link to the okTurtles Foundation donation page here is fine. Text can say something like:

> Donations to the okTurtles Foundation go to supporting the development of Group Income and related projects

2018-09-07 23:26 UTC, taoeffect requested changes
See comments!

2018-09-08 02:43 UTC, dotmacro commented on README.md
> +[![Bitcoin](https://img.shields.io/badge/donate-BTC-blue.svg)](https://okturtles.org/donate/) [![ETH](https://img.shields.io/badge/donate-ETH-blue.svg)](https://okturtles.org/donate/) [![Litecoin](ht
shields.io only supports colored text/emoji/logos on the lefthand side of the button. The ❤️ also ends up off-center:
![](https://img.shields.io/badge/donate-%E2%9D%A4%EF%B8%8F-blue.svg)

One option is to use other emoji/text (but not spaces) can be used to center the righthand side:
![](https://img.shields.io/badge/donate%20-%3D%E2%9D%A4%EF%B8%8F-blue.svg)

Alternatively, if we want a red ❤️, we can create a custom svg that resembles the other buttons.

2018-09-08 02:58 UTC, dotmacro commented on README.md
> +[![Bitcoin](https://img.shields.io/badge/donate-BTC-blue.svg)](https://okturtles.org/donate/) [![ETH](https://img.shields.io/badge/donate-ETH-blue.svg)](https://okturtles.org/donate/) [![Litecoin](ht
From our chat: 
> Lets use this one:
> ![](https://img.shields.io/badge/donate%20-%3D%E2%9D%A4%EF%B8%8F-blue.svg)

2018-09-14 22:21 UTC, taoeffect commented
This is almost ready to merge, only one issue: when I view [the preview of the file](https://github.com/okTurtles/group-income-simple/blob/9a9dd445683d0e589cd450ecba35d2e98b469210/README.md) in safari, this is what I see:

![screen shot 2018-09-14 at 6 20 35 pm](https://user-images.githubusercontent.com/138706/45577645-f73f1f80-b84a-11e8-981a-ca16eaeceea8.jpg)

There's a little square on the end of the button for some reason.

2018-09-14 22:55 UTC, dotmacro commented
Good catch! I removed the utf-8 that wasn't being rendered. Button now renders properly in Safari, Firefox, and Chrome.

2018-09-14 22:56 UTC, merged