fix: #618 solve sourcemaps conflicts with rollup-plugin-vue
okTurtles/group-income pull request #629
Opened 2019-08-21 12:23 UTC by sandrina-p

Closes #618 for good this time.

Based on this comment https://github.com/vuejs/rollup-plugin-vue/issues/238#issuecomment-523133535

> Not a "fix" but a plausible solution was committed in [3f879f3](https://github.com/vuejs/rollup-plugin-vue/commit/3f879f384c39887dc21e359cee9aaa8abdd39079)
> 
> It seems it has to do with how rollup's `watch` works and the source maps accumulating in the plugin. To bypass the issue, set `needMap` to `false` in your options:
> 
> ```
> config.plugins.push(vue({
>     needMap: false,
> }));
> ```
> 
> I am using TypeScript and haven't found issues with the source maps even after adding `needMap: false`, so there's that, YMMV though

Tested in several files and it did work :tada:

2019-08-22 02:14 UTC, taoeffect commented
It's not clear to me what this flag does. Does it simply disable sourcemaps? We already have a rollup config option to do that?

2019-08-22 07:54 UTC, sandrina-p commented
@taoeffect yes, it disables `sourcemaps`, but we still have those because there's another plugin on rollup also creating the sourcemaps. What's why the conflict of sourcemaps, because there were two tools doing the same and now it's only one

2019-08-22 15:55 UTC, taoeffect commented
Although I could be wrong, my understanding is that each plugin needs to generate its own sourcemaps. By disabling the Vue.js sourcemaps it means we won't get to see the original Vue.js source. :-\

2019-08-22 17:10 UTC, taoeffect requested changes
We can add this by way of environment variable. Can you move `DISABLE_SOURCEMAPS` functionality from the `sourcemap` key to this `needMap` key? It's currently here:

```js
        sourcemap: !process.env.DISABLE_SOURCEMAPS && development,
```

Then you should be able to set `needMap: !process.env.DISABLE_SOURCEMAPS` and run `grunt dev` like so: `DISABLE_SOURCEMAPS=1 grunt dev`

2019-08-23 08:52 UTC, sandrina-p commented
@taoeffect 
> Although I could be wrong, my understanding is that each plugin needs to generate its own sourcemaps if it modifies the code. By disabling the Vue.js sourcemaps it means we won't get to see the original Vue.js source. :-\

Have you tried it? Because it works just fine as it is, source maps working correctly.

And we don't need `DISABLE_SOURCEMAPS` flag so I removed it too.

2019-08-25 01:33 UTC, taoeffect approved these changes
OK, I begrudgingly approve this PR, even though it's still not clear to me what this flag is doing, but it does seem to generate the sourcemaps... so... I guess I can't say "no" 😝

2019-08-25 01:33 UTC, merged