Cypress fix
okTurtles/group-income pull request #639
Opened 2019-08-28 04:03 UTC by taoeffect

Includes all changes from #625 (squashed) + fixes + modifications + improvements to other areas (like Docker support).

Run the tests:

```
# all tests
grunt test

# all tests while skipping build step
grunt test --skipbuild

# unit tests only
grunt test:unit

# unit tests while skipping build step
grunt test:unit --skipbuild

# show tests live in a browser
grunt test --browser
grunt test --browser --skipbuild

# run Cypress in "open" mode
grunt test --browser=debug
```

This PR has already been squash-merged, so *please _DO NOT_ squash-merge this PR. Regular-merge only (to preserve stats).*

2019-08-28 07:45 UTC, sandrina-p requested changes
It seems the black magic under pubsub made this work eheh. I left some questions and notes.

2019-08-28 07:45 UTC, sandrina-p commented on .Gruntfile.babel.js
> +  grunt.registerTask('test:unit', ['build', 'backend:launch', 'exec:test'])
Why `test:unit` doesn't need `connect` task as `test`?

2019-08-28 07:45 UTC, sandrina-p commented on .Gruntfile.babel.js
> +      require('~/backend/pubsub.js') // hack to register 'backend/pubsub/setup' selector
I find this comment hard to understand...

> ~if we are not being run with 'grunt test'~, when in watch mode, tell Primus... (...),
> (...) and ~this~ this block will be  (....)

2019-08-28 07:45 UTC, sandrina-p commented on test/cypress/plugins/index.js
> +// }
Why do we have this commented?

2019-08-28 07:45 UTC, sandrina-p commented on test/cypress/integration/signup-and-login.spec.js
> +/* eslint-env mocha */
I believe we don't need this comment in `cypress/` files. Please remove them across all cypress files.

2019-08-28 15:05 UTC, taoeffect commented on .Gruntfile.babel.js
> +  grunt.registerTask('test:unit', ['build', 'backend:launch', 'exec:test'])
Because the server on port 8000 isn't needed for those tests, only the API server is needed.

2019-08-28 15:07 UTC, taoeffect commented on test/cypress/plugins/index.js
> +// }
I didn't know why you added this plugin to the project, since it wasn't needed, but I didn't delete it in case it turns out useful in the future.

2019-08-28 15:10 UTC, taoeffect commented on test/cypress/integration/signup-and-login.spec.js
> +/* eslint-env mocha */
OK, it's not needed because we have `eslint-plugin-cypress` installed, but otherwise it would be. I personally think it should be there as a reminder of that fact, but I'll go ahead and remove it.

2019-08-28 15:11 UTC, taoeffect commented on .Gruntfile.babel.js
> +      require('~/backend/pubsub.js') // hack to register 'backend/pubsub/setup' selector
It's not about watch mode, but about `grunt dev`, so I'll modify the comment to make that clearer

2019-08-29 10:49 UTC, sandrina-p commented on .Gruntfile.babel.js
> +      require('~/backend/pubsub.js') // hack to register 'backend/pubsub/setup' selector
Okay thanks

2019-08-29 10:51 UTC, sandrina-p commented on test/cypress/plugins/index.js
> +// }
I left a comment explaining it. So Cypress shares the same .babelrc than us. In practice, it allows support to FlowJS, for example. If you don't want to, you can delete it, it's pretty easy to add it back (it's explained in Cypress documentation).

2019-08-29 15:21 UTC, taoeffect commented on test/cypress/plugins/index.js
> +// }
What is the problem with leaving the comment here? I do not see the harm.

It's also not clear to me that Browserify is even being used with the way we're using Cypress..

2019-08-29 15:22 UTC, sandrina-p commented on test/cypress/plugins/index.js
> +// }
Ah nevermind, one thing at the time then. Let's merge this!

2019-08-29 15:25 UTC, sandrina-p approved these changes

2019-08-29 15:25 UTC, merged