Replace grunt-svg-sprite for our own SVG compression script
okTurtles/group-income pull request #678
Opened 2019-09-21 14:26 UTC by sandrina-p

Closes #676

2019-09-21 14:27 UTC, sandrina-p commented on .Gruntfile.babel.js
> -        .replace(/height="[a-zA-Z0-9:]*"/, '')
Note: As I explained at https://github.com/svg/svgo/issues/871#issuecomment-533801800, it seems this was a bug from svg-sprite, not SVGO itself. So we don't need to do it manually anymore.

2019-09-23 15:38 UTC, taoeffect requested changes
So, quick note about process here: if you decide to do a different solution to an issue, that needs to be discussed in the issue before a PR is submitted. Since this PR does not close #676 (the solution is different), I'm marking this as "request changes" for now, and we can discuss on the Monday call.

2019-09-24 09:06 UTC, sandrina-p commented
@taoeffect removed SVGO as a dependency. Now SVGs are compressed manually using [SVGOMG](https://jakearchibald.github.io/svgomg/). I updated the SVG README to reflect that.

I would like just to mention I don't agree we do it manually when we have an automated way of doing it. However, I understand the goal of reducing dependencies from this project, so let's move on with this.

2019-09-25 16:16 UTC, taoeffect approved these changes
Excellent! 🙌

2019-09-25 16:16 UTC, merged