Create the dummy UI of Invite links section on GroupSettings page
okTurtles/group-income pull request #707
Opened 2019-10-17 06:05 UTC by SebinSong

related to issue #664 
- This is the dummy UI for the section.
- Currently the content of the table is the **dummy data** I created(in GroupSettings.vue) based on the design mock-up but will be changed to use the real data after the related PR is merged.

Things not yet done but to be implemented later.(soon..!)
- The table is not yet added to the DesignSystem.vue
- Copy/Share functionality of the invite link

2019-10-17 06:23 UTC, SebinSong commented
Sorry, Let me work on Cypress Error!

2019-10-17 07:59 UTC, sandrina-p requested changes

2019-10-17 07:59 UTC, sandrina-p commented on frontend/assets/style/components/_tables.scss
> +table.table {
Can it be just `.table`?

2019-10-17 07:59 UTC, sandrina-p commented on frontend/assets/style/components/_tables.scss
> +  width: 100%;
By default a `table` already has `table-layout: fixed` and `width: 100% `

2019-10-17 07:59 UTC, sandrina-p commented on frontend/assets/svgs/compressed/access.svg
> +<?xml version="1.0" encoding="utf-8"?><svg viewBox="0 0 123 86" fill="none" xmlns="http://www.w3.org/2000/svg" width="123" height="86"><path fill-rule="evenodd" clip-rule="evenodd" d="M25.72 7.88a2.4
There's something odd here. these icons inside compressed folder should be discard. The icons are directly inside `/assets/svgs/`

2019-10-17 07:59 UTC, sandrina-p commented on frontend/views/components/GroupSettings/InviteActionButton.vue
> +      default: false
if the default is false, we can do just `isLinkExpired: Boolean`

2019-10-17 07:59 UTC, sandrina-p commented on frontend/views/components/GroupSettings/InviteActionButton.vue
> +  margin-right: 16px;
```
16px = $spacer;
-0.5rem = $spacer-sm;
```

2019-10-17 07:59 UTC, sandrina-p commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +      | {{ ephemeral.activeOn? L('Active links') : L('All links') }}
missing white space before `?`

2019-10-17 07:59 UTC, sandrina-p commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +        th.action
even if it doesn't have visual text, it should have a a11y text using aria-label with L()

2019-10-17 07:59 UTC, sandrina-p commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +            :isTextCenter='true'
discuss with @mmbotelho , but I think this share tooltip should be placed bellow to the left, so in small screens it isn't cutted like here:
<img width="319" alt="image" src="https://user-images.githubusercontent.com/14869087/66988376-19991180-f0cb-11e9-9aa1-9aabb1d47589.png">

2019-10-17 07:59 UTC, sandrina-p commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +          div
I believe we don't need this extra div

2019-10-17 07:59 UTC, sandrina-p commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +              :class='item.state.isExpired ? "expired" : ""'
classes that reflect a "state" should start with `is-`

2019-10-17 07:59 UTC, sandrina-p commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +  },
remove this

2019-10-17 07:59 UTC, sandrina-p commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +      type: Array
it would be nice to add a comment explaining the structure of this array

2019-10-17 07:59 UTC, sandrina-p commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +  .name {
don't forget to add `.c-` in classes used only on components.

2019-10-17 07:59 UTC, sandrina-p commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +    div {
avoid using global selectors to style, prefer using a class

2019-10-17 07:59 UTC, sandrina-p commented on frontend/views/pages/GroupSettings.vue
> +  )
this can all be in one single line

2019-10-17 08:03 UTC, sandrina-p commented on frontend/views/components/GroupSettings/InviteActionButton.vue
> +  name: 'inviteActionButton',
i think this file should be called `InviteLinksActionButton` to follow the same name as the other file. the same for the component name.

2019-10-17 08:58 UTC, taoeffect commented on frontend/views/components/GroupSettings/InviteActionButton.vue
> +        | Revoke link
Here and in a few other places, remember to use `i18n`, i.e. write this as:

```
i18n.icon-times.c-icon(tag='i') Revoke link
```

2019-10-17 09:00 UTC, taoeffect commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +        i18n.state(tag='th') state
@SebinSong now after our discussion you should have a better understanding of i18n, and see that i18n strings must be complete sentences, or the localizer will not have the context to translate them. So these 3 tags need to be collapsed into one. If you need HTML, use the `html=` attribute. Search the code for `html=` to see examples of how to pass HTML into i18n.

2019-10-17 09:01 UTC, taoeffect commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +  // TODO: figuring out using either i18n or L() for the tag below
Use i18n with html tag (see other comment)

2019-10-18 08:23 UTC, SebinSong commented on frontend/assets/svgs/compressed/access.svg
> +<?xml version="1.0" encoding="utf-8"?><svg viewBox="0 0 123 86" fill="none" xmlns="http://www.w3.org/2000/svg" width="123" height="86"><path fill-rule="evenodd" clip-rule="evenodd" d="M25.72 7.88a2.4
I'm not so sure why these svg files are considered as new content here..! :(

2019-10-18 08:23 UTC, SebinSong commented on frontend/assets/style/components/_tables.scss
> +table.table {
Fixed!

2019-10-18 08:23 UTC, SebinSong commented on frontend/assets/style/components/_tables.scss
> +  width: 100%;
Good Info! Fixed!

2019-10-18 08:23 UTC, SebinSong commented on frontend/assets/svgs/compressed/access.svg
> +<?xml version="1.0" encoding="utf-8"?><svg viewBox="0 0 123 86" fill="none" xmlns="http://www.w3.org/2000/svg" width="123" height="86"><path fill-rule="evenodd" clip-rule="evenodd" d="M25.72 7.88a2.4
So, would you advise me to delete the entire `/compressed` folder here? (I'm not sure how this folder has been generated in my working repository if it has already been removed from other PR :) )

EDIT: Since `master` doesn't have the `/compressed` folder like you pointed out, I just deleted them.

2019-10-18 08:23 UTC, SebinSong commented on frontend/views/components/GroupSettings/InviteActionButton.vue
> +        | Revoke link
Fixed! Thnx :)

2019-10-18 08:23 UTC, SebinSong commented on frontend/views/components/GroupSettings/InviteActionButton.vue
> +  name: 'inviteActionButton',
Makes sense :) Fixed!

2019-10-18 08:23 UTC, SebinSong commented on frontend/views/components/GroupSettings/InviteActionButton.vue
> +      default: false
Yuup!!

2019-10-18 08:23 UTC, SebinSong commented on frontend/views/components/GroupSettings/InviteActionButton.vue
> +  margin-right: 16px;
Fixed! :)

2019-10-18 08:23 UTC, SebinSong commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +      | {{ ephemeral.activeOn? L('Active links') : L('All links') }}
Yup!

2019-10-18 08:23 UTC, SebinSong commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +        i18n.state(tag='th') state
![TheyAreColumnNames](https://user-images.githubusercontent.com/17641213/66997229-8ee9fe00-f12e-11e9-801b-554ac60656a1.png)

Yeah, but these can't be collapsed into one here because the three represent the column names in this table. :) But the fact that each of them is neither a complete sentence nor a word that can stand alone can be definitely problematic in terms of localization. Should this be discussed with Margarida?

2019-10-18 08:23 UTC, SebinSong commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +        th.action
That's a good point to note. thnx!! and fixed!

2019-10-18 08:23 UTC, SebinSong commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +          div
You are right! fixed!

2019-10-18 08:23 UTC, SebinSong commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +            :isTextCenter='true'
Yup. fixed!.

2019-10-18 08:23 UTC, SebinSong commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +  },
Yup. removed 'groupMembers' getter as well.

2019-10-18 08:23 UTC, SebinSong commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +      type: Array
Yup. Since currently it's implemented with dummy data I arbitrarily created, I left it as a `// TODO:` comment, so I could get it done when we re-implement it with the real data.

2019-10-18 08:23 UTC, SebinSong commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +  .name {
yup. fixed!

2019-10-18 08:23 UTC, SebinSong commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +    div {
Fixed!

2019-10-18 08:23 UTC, SebinSong commented on frontend/views/pages/GroupSettings.vue
> +  )
fixed!

2019-10-18 08:23 UTC, SebinSong commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +  // TODO: figuring out using either i18n or L() for the tag below
Fixed. But this solution produces an issue where `<router-link></router-link>` doesn't work. I left a `// TODO:` comment regarding this.

2019-10-18 08:30 UTC, taoeffect commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +        i18n.state(tag='th') state
I didn't realize they were table headings... oops! All good

2019-10-18 09:17 UTC, taoeffect commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +    i18n.has-text-1 Here's a list of all invite links you own
Remember, `i18n` can specify the tag, so save a line with:

```
i18n.c-invite-description.has-text-1(tag='p') Here's a list of all invite links you own
```

2019-10-19 05:39 UTC, mmbotelho submitted a review, later dismissed
Great job!!

2019-10-19 06:31 UTC, taoeffect commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +            button.is-icon-small(v-if='item.name === "Anyone"')
This link needs to have a special property on it to check it, for example, you can add a `isAnyoneLink` property to just that link, set it to `true`, and check that here

2019-10-19 06:35 UTC, taoeffect commented on frontend/views/components/GroupSettings/InviteLinks.vue
> +            i.icon-copy.is-regular
Can you implement clicking the icon to copy the link?

2019-10-19 08:44 UTC, taoeffect commented
Closing to see if Cypress integration works. Please re-open as another pull request.

2019-10-19 08:44 UTC, closed without merging