Fix/create card banner fix dropdown styles and router issue
okTurtles/group-income pull request #730
Opened 2019-10-20 11:50 UTC by sandrina-p

- Create card banner component
- Fix dropdown styles
- Add reduced-motion feature (enabled by default on Cypress) and try to fix #696

2019-10-20 12:05 UTC, taoeffect reviewed
This looks good! Only concern I have at the moment is whether "Banner" is a good name for the new component you created, since @mmbotelho has designed something called "Banners" and already is using them for a very different purpose here: #688.

To me the "Banner" here looks more like a card of some sort:

<img width="754" alt="Screen Shot 2019-10-20 at 3 03 46 PM" src="https://user-images.githubusercontent.com/138706/67159278-085e3800-f34b-11e9-91ec-c57f48019888.png">

Maybe a different name can be picked to save "Banner" for the things in #688?

2019-10-20 12:16 UTC, mmbotelho commented
We can call them _Callout Cards_ instead, as in [Shopify's Polaris](https://polaris.shopify.com/components/structure/callout-card#navigation).

@sandrina-p @taoeffect

2019-10-20 12:30 UTC, mmbotelho requested changes
- The dropdowns have the wrong font - should be body text;
- The dropdown list-item should be 32px high (the implemented version has 40-something px);
- This spacing:
<img width="752" alt="Captura de ecrã 2019-10-20, às 15 22 30" src="https://user-images.githubusercontent.com/22004566/67159501-1d889600-f34e-11e9-8e8d-ab66836501e6.png">


Other than that I couldn't find anything else wrong. I am not happy at all with how it looks on mobile, but that's work for me, don't worry about it 😄

2019-10-20 13:41 UTC, mmbotelho submitted a review, later dismissed
Great job! 🎉

2019-10-20 13:46 UTC, taoeffect commented on frontend/views/containers/settings/Appearence.vue
> +        .help When enabled the amount of animations you see around are reduced.
missing i18n here and on line 9

2019-10-20 13:48 UTC, taoeffect requested changes
Minor i18n thing in appearance, once that's fixed it's GTD!

2019-10-20 14:27 UTC, taoeffect commented on frontend/views/containers/settings/Appearence.vue
> +      h2.settings-subtitle Reduced Motion
"and on line 9" :)

2019-10-20 14:27 UTC, taoeffect commented on frontend/views/containers/settings/Appearence.vue
> +      h2.settings-subtitle Reduced Motion
Noticing, on line 17 too

2019-10-20 14:29 UTC, taoeffect commented on test/cypress/support/commands.js
> +Cypress.Commands.add('giLogout', ({ hasNoGroup = false } = {}) => {
this doesn't seem like valid javascript?

2019-10-21 06:14 UTC, merged

2019-10-21 06:15 UTC, taoeffect commented
**NOTE: this is an exceptional merge that violates Rule 7 of our contributions guidelines because it's during a hackathon and I have approval from @sandrina-p to merge it, and @sandrina-p cannot merge it herself because the build is failing, but it's an error unrelated to this PR.**