WIP Task / 561 Implement the "Group members" page #809
okTurtles/group-income pull request #818
Opened 2020-02-01 09:04 UTC by pieer

2020-02-04 16:38 UTC, mmbotelho requested changes
This is looking great! I noticed a couple of details:

- It's missing a "clear field" button (see images below);
- The number of results and query entered should be highlighted (see image below);
- When there are 0 results, can we change the copy to "Sorry, we couldn't find anyone called [xyz]."

<img width="582" alt="Captura de ecrã 2020-02-04, às 17 33 50" src="https://user-images.githubusercontent.com/22004566/73765455-db585880-4774-11ea-950d-5af085b6386e.png">
<img width="642" alt="Captura de ecrã 2020-02-04, às 17 34 33" src="https://user-images.githubusercontent.com/22004566/73765472-df847600-4774-11ea-8767-6df8ec825b49.png">

Other than that, it's looking great! 😄

2020-02-04 17:58 UTC, sandrina-p reviewed
Besides the table thing, I didn't notice any other major issue.

2020-02-04 17:58 UTC, sandrina-p commented on frontend/views/containers/dashboard/GroupMemberMenu.vue
> +  name: 'GroupMembers',
`GroupMembersMenu`

2020-02-04 17:58 UTC, sandrina-p commented on frontend/views/containers/dashboard/GroupMemberMenu.vue
> +  margin-left: -182px;
use rem here on both 2 rules.

2020-02-04 17:58 UTC, sandrina-p commented on frontend/views/containers/dashboard/GroupMembersAllModal.vue
> +          .input-combo
An input should always have a label, even when invisible, for screen readers.
```
i18n.sr-only Search for a member
```

2020-02-04 17:58 UTC, sandrina-p commented on frontend/views/containers/dashboard/GroupMembersAllModal.vue
> +.c-menu {
Where's this class used? Seems lost.

2020-02-04 17:58 UTC, sandrina-p commented on frontend/views/containers/dashboard/GroupMembersAllModal.vue
> +          tr.c-group-member(
This for me is a list of results, not a table. In terms on A11Y there are some issues here (ex: using `display: flex` in a table element removes its semantics (the same way we use `display: none` to hide something))

So, I would advise to just replace `table` for `ul li` and everything gets easier.

2020-02-04 17:58 UTC, sandrina-p commented on frontend/views/containers/dashboard/GroupMembersAllModal.vue
> +  margin-left: .5rem;
we have the class `.buttons` for this same purpose. In this case we just need to remove the `margin-top` that comes from it.

2020-02-05 12:10 UTC, mmbotelho requested changes
<img width="605" alt="Captura de ecrã 2020-02-05, às 13 07 17" src="https://user-images.githubusercontent.com/22004566/73840524-a30a5600-4818-11ea-9ac5-24e683430d22.png">

I thought I had specified the interaction for the search input with the clear button but it wasn't on Figma, my mistake! I added it there, here's how it should look: 
<img width="507" alt="Captura de ecrã 2020-02-05, às 13 09 58" src="https://user-images.githubusercontent.com/22004566/73840613-d64ce500-4818-11ea-9839-c399f49f7e7d.png">

2020-02-05 18:23 UTC, sandrina-p commented on frontend/views/containers/dashboard/GroupMembersAllModal.vue
> +        .filter(profile => profile, [])
What's the 2nd parameter `[]` for?

2020-02-05 18:23 UTC, sandrina-p submitted a review, later dismissed
looks good, great work @pieer!

2020-02-06 00:10 UTC, taoeffect requested changes
Nice job @pieer, left some comments. I wasn't able to finish my review because I couldn't figure out how to bring up the modal during manual testing.

Speaking of tests, this PR is missing them! Please add a test that brings up the modal, does a search, verifies the search results are correct, and then closes the modal.

2020-02-06 00:10 UTC, taoeffect commented on frontend/views/containers/dashboard/GroupMembersAllModal.vue
> +          compile
If the HTML you're using doesn't contain any Vue-specific components (as is the case here and below on line 41), you don't need to add the `compile` to the attributes. It should render correctly and faster without it.

2020-02-06 00:10 UTC, taoeffect commented on frontend/views/containers/dashboard/GroupMembersAllModal.vue
> +        ) Showing {searchCount} {result} for "{searchTerm}"
You did a great job constructing this string a really readable and translator-friendly manner 👍

2020-02-06 00:10 UTC, taoeffect commented on frontend/views/containers/dashboard/GroupMemberMenu.vue
> +        i18n Send message
Strangely, clicking this does nothing?

2020-02-06 00:10 UTC, taoeffect commented on frontend/views/containers/dashboard/GroupMembersAllModal.vue
> +  name: 'IncomeDetails',
The name of this component should be the same as the file

2020-02-06 00:10 UTC, taoeffect commented on frontend/views/containers/dashboard/GroupMembersAllModal.vue
> +            return { username, name, displayName }
Note that `name` is the same as `username`, so it can and probably should be ignored in favor of `username`.

2020-02-06 00:10 UTC, taoeffect commented on frontend/views/containers/dashboard/GroupMembersAllModal.vue
> +        .filter(profile => profile, [])
Yeah, I don't think the `[]` is needed there. It's also not super clear to me what this `.filter` is doing..? Maybe the condition should be something like `!!profile` or `profile !== undefined` to be a little clearer?

2020-02-06 06:35 UTC, sandrina-p commented
Regarding the cypress tests, one suggestion for you @pieer:
Since we have bypass-ui for signup/login but don't for acceptInvitation, I would do this flow:

- loop to signup 12 users (with bypassUI) and logout,
- user1 creates a group,
-  loop to login userX and accept Invitation.

or the most correct way: - create acceptInvitation bypass-ui action and do it directly without the need to signup/logout and login again.

2020-02-08 23:27 UTC, taoeffect commented on frontend/views/containers/dashboard/GroupMemberMenu.vue
> +        i18n Send message
In `router.js` this is currently bound to the route `'/messages/:chatName'`

2020-02-08 23:29 UTC, taoeffect commented on frontend/views/containers/dashboard/GroupMembersAllModal.vue
> +          compile
Yep, just tested this and it's not needed. I see you already removed the one on line 41, don't forget about this one too!

2020-02-08 23:31 UTC, taoeffect commented on frontend/views/containers/dashboard/GroupMembersAllModal.vue
> +      this.$router.push({ path: '/chat' })
Same issue [as above](https://github.com/okTurtles/group-income-simple/pull/818/files#r376741116), I don't think `/chat` is a valid route, but `/messages` seems to be? Dunno, that stuff is also not implemented, so it's up to you whether you want to change it or leave it as-is for now.

2020-02-08 23:32 UTC, taoeffect requested changes
@pieer this is looking excellent, I just tested it and it works.

Minor changes requested, see comments. The other thing is, can you add a single test that does a quick search for a `displayName` and verifies the results list returns the correct number of rows?

2020-02-09 15:30 UTC, mmbotelho approved these changes
Approved! Great job @pieer 🎉

2020-02-09 16:33 UTC, taoeffect approved these changes
Excellent work @pieer!

2020-02-09 16:33 UTC, merged