Improve form elements layout (#831 #833
okTurtles/group-income pull request #862
Opened 2020-03-13 17:59 UTC by sandrina-p

Close #831, #833 and #861 

### Scouting rule:
- Reviewed all form elements. There were some with incorrect error styling.
- Add to DS form fields: `switch`, `combobox` and `search`.
- Inputs that need a decimal keyboard (ex: mincome) changed from `type="number"` to `inputmode="decimal"`. See [reference] and [available inputmodes](https://inputmodes.com/).
- Add  `@mixin icon` to use when a icon is used as pseudo element.
- Add `menu` example to DS.

2020-03-16 09:04 UTC, pieer submitted a review, later dismissed

2020-03-16 09:04 UTC, pieer commented on frontend/views/components/Search.vue
> +    .inputGroup.c-search
Why this one is camel case

2020-03-17 14:49 UTC, sandrina-p commented on frontend/views/components/Search.vue
> +    .inputGroup.c-search
I was undecided too... Changed to `.inputgroup` as it's done with `.selectbox`.

2020-03-18 10:58 UTC, sandrina-p commented on frontend/assets/style/components/_combobox.scss
> +.selectsolo {
Note: A combo field in the web usually means it is a select box where each child has multiple elements, (ex: a list of countries with flags) or it has some built it functionality (ex: a search within the select list).

This element is just a simple select box that can be used solo in the page (ex: nr of items per page). That's why I think `.selectsolo` is a better name than `.combobox`.

2020-03-19 16:36 UTC, mmbotelho requested changes
Here's what I found:

- The password input is not working as expected on the DS (it's working properly on the login though). It's not very important, just a heads up:
<img width="514" alt="Captura de ecrã 2020-03-19, às 16 33 48" src="https://user-images.githubusercontent.com/22004566/77090784-8c524400-69ff-11ea-9c88-a8255d1fdd8e.png">

<img width="840" alt="Captura de ecrã 2020-03-19, às 16 32 31" src="https://user-images.githubusercontent.com/22004566/77090779-8a888080-69ff-11ea-974c-0a0ecc09d8b4.png">

2020-03-20 09:52 UTC, sandrina-p commented on frontend/assets/style/components/_combobox.scss
> -.combobox {
Note: It wasn't deleted. It was renamed to `_selectsolo.scss`

2020-03-20 09:52 UTC, sandrina-p commented on frontend/assets/style/components/_selectsolo.scss
> +.selectsolo {
combobox usually refers to a custom select element with aditional behavior, just as a built-in search within the select options or with custom options (ex: a list of countries with flags).
This element is just a simple selectbox but it can be used anywhere as a solo element. That's why I believe `selectsolo` is a better name than `combobox`

2020-03-20 10:15 UTC, sandrina-p commented
@mmbotelho,
The DS page is focused in showing the UI and sometimes the functionality is dumb or missing (ex: the input to remove the invitation does not work).

But anyway, I made the password toggle work there, just for you :p
Regarding the `.selectGroup`, each scenario needs to manually define the select width for technical reasons. If you go to "the real places" where it's used, it's all fine. But, once again, I fixed it on DS page too and documented this constraint on the code too.

2020-03-20 19:07 UTC, mmbotelho approved these changes
Good job, approved!

2020-03-23 03:34 UTC, pieer approved these changes
Great work!

2020-03-23 15:22 UTC, merged