Remove spacer
okTurtles/group-income pull request #864
Opened 2020-03-16 08:56 UTC by pieer

2020-03-17 15:02 UTC, sandrina-p commented
@pieer this PR has 80 commits... It seems you created this branch from your previous PR branch (#851) instead of master. I think this will create massive conflicts when we try to merge it with master.

To simplify you can just create a new brand branch (from master!) and cherry pick this single commit "75595de - Remove all spacer variable except form" to it and create a new PR.

2020-03-17 15:30 UTC, pieer commented
It's already merge with master @sandrina-p. And if you just squash merge you won't see any difference I believe?

2020-03-17 16:05 UTC, sandrina-p requested changes
What I've seen it's all good, it seems a pretty direct find-replace approach.
Still, I noticed `$spacer` variables around still existing. Look for `$spacer` in the whole project. There are still 24 files to change.

![image](https://user-images.githubusercontent.com/14869087/76875863-0a301700-6869-11ea-927b-80f572d9454f.png)

2020-03-17 16:05 UTC, sandrina-p commented on frontend/assets/style/_variables.scss
> +// TODO remove once Sandrina changes are done (next commit)
👍

2020-03-17 16:05 UTC, sandrina-p commented on frontend/assets/style/components/_cards.scss
> +
This code is new... but I think it was already in master. What's wrong here?

2020-03-17 16:05 UTC, sandrina-p commented on frontend/views/components/Page.vue
> +    width: calc(100% - #{4rem});
no need to have `#{}` here

2020-03-17 16:05 UTC, sandrina-p commented on frontend/views/components/menu/MenuHeader.vue
> +  padding: 0.5rem 1rem 0.5rem 1rem;
`padding: 0.5rem 1rem` is enough

2020-03-17 16:05 UTC, sandrina-p commented on frontend/views/pages/DesignSystem.vue
> +              | 2rem
Odd... i think this line doesn't make sense and it should be removed.

2020-03-19 18:41 UTC, taoeffect commented
Wait, what issue is this closing? It's important that the problem/solution be clearly documented.

2020-03-20 08:44 UTC, sandrina-p commented
@taoeffect this PR solves https://github.com/okTurtles/group-income-simple/issues/859

2020-03-23 13:54 UTC, pieer commented on frontend/assets/style/components/_cards.scss
> +
Nothing, all good

2020-03-23 14:51 UTC, sandrina-p submitted a review, later dismissed
Yey, one step closer to say bye-bye to `$spacer` variables :D

2020-04-06 15:22 UTC, taoeffect approved these changes
Fantastic! 💪

2020-04-06 15:22 UTC, merged