#778 improve modal keyboard navigation
okTurtles/group-income pull request #888
Opened 2020-04-11 14:06 UTC by sandrina-p

Closes #778 

![Apr-11-2020 14-49-02](https://user-images.githubusercontent.com/14869087/79045777-be248800-7c04-11ea-8723-7a4de7be6ebf.gif)

### Improvements made
- The keyboard navigation inside the modal: it works as expected: when reaching the last interactive element the next `Tab` does back to the first element and vice-versa.
- The "solid" buttons didn't change background color on `:focus`, now they do (as in DS).
- Add a required prop to modal: `a11yTitle` so that SR (screen readers) can read correctly what's the modal about when they start to interact with it.

2020-04-13 10:53 UTC, pieer submitted a review, later dismissed

2020-04-14 02:50 UTC, dotmacro commented
Log in modal works great! :-D 

Tab still misses the "Log in" _link_ in the footer of the sign up modal. (Should it also be a button, like "Create an account" in the footer of the Log In modal?)
<img width="668" alt="Screen Shot 2020-04-13 at 7 25 49 PM" src="https://user-images.githubusercontent.com/13082264/79179589-ccb59f80-7dbc-11ea-8a29-fd2083d475c9.png">

Scout rule: "Login" button should say "Log in" with a space, just like the modal title. (line 27 of LoginForm.vue)

2020-04-14 19:50 UTC, taoeffect requested changes
Just one minor copy issue related to "Login" vs "Log In" (Andrea noticed we've been writing that incorrectly) + if you can see if you can fix the issue she noticed with consistent tab behavior between Log In and Sign Up modals.

2020-04-14 19:50 UTC, taoeffect commented on frontend/views/containers/access/LoginModal.vue
> +  modal-template(class='has-background' ref='modal' :a11yTitle='L("Login")')
Andrea noticed that we've been writing "Login" incorrectly, it should be "Log In"

2020-04-14 21:12 UTC, sandrina-p commented
@dotmacro the "Log in" link is fixed now and accessible by keyboard!

> Should it also be a button, like "Create an account" in the footer of the Log In modal?

Yes, it should be a button. Before it was a `<a>` tag without `href=''`. An `<a>` element is only keyboard accessible when it has a non-empty href attribute. `<a>` or `<a href="">` should not be used for links. In this case it must be a `<button>`. [webAIM reference](https://webaim.org/techniques/keyboard/)

2020-04-14 21:15 UTC, taoeffect approved these changes
👍

2020-04-14 21:15 UTC, merged