#872 Add dark theme
okTurtles/group-income pull request #911
Opened 2020-05-04 10:03 UTC by pieer

2020-05-04 11:24 UTC, mmbotelho commented
Note: This PR closes #872

2020-05-04 11:42 UTC, mmbotelho submitted a review, later dismissed
@pieer this is looking great! I found zero mistakes! 

However, there are things I'm not 100% happy with in terms of design, mainly how bright and colorful everything is. I really think I need to tone things down a bit and make them more neutral. But well, that's not related to your PR. 

Great job! 🎉

2020-05-04 14:47 UTC, sandrina-p submitted a review, later dismissed
Nothing to point out regarding the code! Awesome work!

2020-05-04 14:47 UTC, sandrina-p commented on frontend/model/state.js
> +    if (!state.theme) state.theme = 'light' // TODO: check color available, prevent setting something differrent than available colors
Do you plan to do this in this PR? If not, open an issue to not be forgotten or update the current one.

2020-05-04 14:47 UTC, sandrina-p commented on frontend/views/components/AppStyles.vue
> +    lighterOrdDarker () {
`softTone` is a good hybrid name that adapts regardless of the theme.

2020-05-06 20:50 UTC, taoeffect commented on frontend/model/state.js
> +}
I don't understand... how is it possible for the state to not have a theme? I don't think this is necessary. Maybe it was a fluke?

2020-05-06 20:51 UTC, taoeffect commented on frontend/views/pages/DesignSystem.vue
> +    button.is-small.dark-team-toggle(@click='toggleTheme') Toggle {{isDarkTheme ? 'Dark' : 'Light' }} Theme
Need `L` usage here, using a computed property for a complete sentence.

2020-05-06 20:52 UTC, taoeffect commented on frontend/views/pages/DesignSystem.vue
> +      this.setTheme(this.isDarkTheme ? 'light' : 'dark')
It's possible that the issue with `checkThemeState` above is due to a typo. Can you convert all these string literals to be string constants? E.g. define in some file `const THEME_LIGHT = 'light'` (same for dark) and import and use it here and elsewhere.

2020-05-06 20:55 UTC, taoeffect requested changes
See comments! I wasn't able to test out the theme also because when I clicked to change it to dark theme nothing happened:

<img width="876" alt="Screen Shot 2020-05-06 at 1 53 29 PM" src="https://user-images.githubusercontent.com/138706/81227390-32064600-8fa1-11ea-8385-57a0cb309721.png">

2020-05-06 21:09 UTC, sandrina-p commented
@taoeffect that's strange... I can test it locally. Did you see any error or so on the console?

2020-05-06 22:04 UTC, taoeffect commented
@sandrina-p no console errors, done in Firefox Developer Edition, using commit b780d43137dc501cdfdc53397861b15eb672936b, which does appear to be the latest shown here on GH.

2020-05-06 22:50 UTC, sandrina-p commented
@taoeffect, you are right. I have locally the first version of this PR. @pieer added two commits after my review and it broke the page. I tried to fix it so you can review it. Here's the fix:

```js
// state.js L192
setTheme (state, color) {
    state.theme = color
},
```

After that, it should work.

2020-05-06 22:52 UTC, taoeffect commented
Good find! Yeah I think the `checkThemeState` stuff can be removed too.

2020-05-08 16:34 UTC, sandrina-p approved these changes

2020-05-08 16:36 UTC, sandrina-p approved these changes

2020-05-08 23:52 UTC, taoeffect approved these changes
Fantastic work @pieer! 🎉

2020-05-08 23:52 UTC, merged