Add pug-lint plugin to validate i18n tag usage
okTurtles/group-income pull request #960
Opened 2020-08-25 08:44 UTC by snowteamer

Related to #607 

* The companion test file should describe what this plugin allows and disallows.
* To keep things simple, this plugin currently defines a single new rule `validateI18n`, which doesn't take any option.
* I was not sure where the new files should go, so for now I have put them under a new `~/pug-lint-rules` folder.

### Boyscout rule
* Fixed the corresponding Grunt task `exec:puglint` to also work on older Windows shells.

2020-09-03 23:19 UTC, sdegutis approved these changes

2020-09-03 23:19 UTC, sdegutis approved these changes, later dismissed
Looks good, thanks.

2020-09-04 15:56 UTC, taoeffect requested changes
Fantastic @snowteamer!

Just two file/organization related changes requested:

- Could you please move `validate-i18n.test.js ` into the `test/` folder and make sure that `grunt test` runs the file
- Place `validate-i18n.js` into the `scripts/` folder and delete the no longer needed `pug-lint-rules` folder to keep the top-level folder from getting too crowded 😄

2020-09-07 22:04 UTC, taoeffect approved these changes
Fantastic, professional job @snowteamer! Very impressive! Approved!

2020-09-07 22:04 UTC, merged